permalink: /about_us/jwg1/sdmr
---
= Syntax DMR Submission Processing Procedures





<nav role="navigation">

<li id="item-4937"  class=" menu-item menu-item-type-post_type menu-item-object-page current-page-ancestor current-menu-ancestor current_page_ancestor menu-item-has-children">link:/about_us"><strong>About Us</strong><span class="navi-description[Who we are</span>]

	<li id="item-5004"  class=" menu-item menu-item-type-post_type menu-item-object-page current-page-ancestor current-menu-ancestor current-menu-parent current-page-parent current_page_parent current_page_ancestor menu-item-has-children">link:/about_us/jwg1[JWG 1 – EDIFACT Syntax]
	
		link:/about_us/jwg1/sdmr[Syntax DMR Procedures]
	
</li>
	link:/about_us/wg3[WG 3 – CCTS]
	link:/about_us/wg4[WG 4 – eLK]
	link:/about_us/cat[CAT -- Chairman's Advisory Team]
	<li id="item-5034"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us/ma[TDED Maintenance Agency]
	
		link:/about_us/ma/membership-of-the-tded-maintenance-agency[Membership of the TDED MA]
		link:/about_us/ma/ma_links[Relevant links to TDED MA folders/files]
	
</li>

</li>
<li id="item-4922"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/projects"><strong>Projects</strong><span class="navi-description[What we do</span>]

	link:/projects/iso-np-6422-2[ISO NP 6422-2]
	link:/projects/iso-np-14533[ISO NP 14533]
	link:/projects/iso-pwi-tr-6422-3[ISO PWI TR 6422-3]
	link:/projects/iso-np-9735-10[ISO NP 9735-10]
	link:/projects/iso-np-15000-5[ISO NP 15000-5]
	link:/projects/iso-np-17369[ISO NP 17369]

</li>
<li id="item-4912"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/standards"><strong>Standards</strong><span class="navi-description[Our output</span>]

	link:/standards/iso-6422-12010[ISO 6422-1:2010]
	link:/standards/iso-73722005[ISO 7372:2005]
	link:/standards/iso-84391990[ISO 8439:1990]
	link:/standards/iso-84401986[ISO 8440:1986]
	link:/standards/iso-86012004[ISO 8601:2004]
	link:/standards/iso-97351988[ISO 9735:1988]
	link:/standards/iso-97351988amd-11992[ISO 9735:1988/Amd 1:1992]
	link:/standards/iso-9735-12002[ISO 9735-1:2002]
	link:/standards/iso-9735-22002[ISO 9735-2:2002]
	link:/standards/iso-9735-32002[ISO 9735-3:2002]
	link:/standards/iso-9735-42002[ISO 9735-4:2002]
	link:/standards/iso-9735-52002[ISO 9735-5:2002]
	link:/standards/iso-9735-62002[ISO 9735-6:2002]
	link:/standards/iso-9735-72002[ISO 9735-7:2002]
	link:/standards/iso-9735-82002[ISO 9735-8:2002]
	link:/standards/iso-9735-92002[ISO 9735-9:2002]
	link:/standards/iso-9735-102002[ISO 9735-10:2002]
	link:/standards/isots-15000-12004[ISO/TS 15000-1:2004]
	link:/standards/isots-15000-22004[ISO/TS 15000-2:2004]
	link:/standards/isots-15000-32004[ISO/TS 15000-3:2004]
	link:/standards/isots-15000-42004[ISO/TS 15000-4:2004]
	link:/standards/isots-15000-52005[ISO/TS 15000-5:2005]
	link:/standards/isots-173692005[ISO/TS 17369:2005]
	link:/standards/isots-206252002[ISO/TS 20625:2002]

</li>
link:/minutes"><strong>Minutes</strong><span class="navi-description[Announcements</span>]
link:/faq"><strong>FAQ</strong><span class="navi-description[Your questions</span>]
link:/isotc-154-2016-anual-meeting-details"><strong>Meetings</strong><span class="navi-description[2016 Meetings</span>]

</nav>
</div><!-- END header-area -->
</div><!-- END header-overlay -->
</div><!-- END header-holder -->
</header><!-- END header -->


<div id="main" class="tt-slider-">


<div class="main-area">

<nav role="navigation" id="sub_nav" class="nav_right_sub_nav">


	<li class="menu-item menu-item-type-post_type menu-item-object-page current-page-ancestor current-menu-ancestor current-menu-parent current-page-parent current_page_parent current_page_ancestor menu-item-has-children">link:/about_us/jwg1[JWG 1 – EDIFACT Syntax]
	
		<li class="menu-item menu-item-type-post_type menu-item-object-page ">link:/about_us/jwg1/sdmr[Syntax DMR Procedures]</li>
	
</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/wg3[WG 3 – CCTS]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/wg4[WG 4 – eLK]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/cat[CAT -- Chairman's Advisory Team]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us/ma[TDED Maintenance Agency]
	
		<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/ma/membership-of-the-tded-maintenance-agency[Membership of the TDED MA]</li>
		<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/ma/ma_links[Relevant links to TDED MA folders/files]</li>
	
</li>

</nav><!-- END sub_nav -->


&nbsp;

== Joint syntax working group (with UNECE)
== Syntax Data Maintenance Request Submission and Processing Procedures

<ol>
<ol>
<li>IntroductionSyntax Data Maintenance Requests (Syntax DMRs) serve as the means to apply enhancements to ISO 9735 (Electronic data interchange for administration, commerce and transport (EDIFACT) — Application level syntax rules). These Syntax DMRs fall into three categories:

<li><strong>Service code DMRs</strong><br />
DMRs proposing changes and/or additions which are against ISO 9735/V.3 and/or ISO 9735/V.4 related to codes for data elements beginning with ‘0’.</li>
<li><strong>Service directory DMRs</strong><br />
DMRs against ISO 9735/V.4 which are related to segments beginning with ‘U’; composite data elements beginning with ‘S’; data elements beginning with ‘0‘.

Service directory DMRs against ISO 9735/V.3 are no longer applicable.</li>
<li><strong>Syntax rule DMRs</strong><br />
DMRs proposing changes or enhancements to any of the syntax rules and associated text specified in the latest release of ISO 9735/V.4 (which includes the service messages AUTACK, CONTRL and KEYMAN).</li>

</li>
</ol>
</ol>
Syntax rule DMRs against ISO 9735/V.3 are no longer applicable.

<ol>
<li>Submission of Syntax DMRs
<ol type="I">
<li>Submission of Service code DMRs
<ol type="i">
* <strong>Service code DMRs</strong> shall be directly submitted to the ISO/TC 154/JWG 1 (JSWG)<a id="refX" href="#X"><sup>[1]</sup></a> using the web form specifically designed for this purpose. The form can be accessed through the JWG 1 web site: <a title="ISO/TC 154 JWG1 Website" href="http://www.gefeg.com/jswg" target="_blank">http://www.gefeg.com/jswg</a>.
<li>In addition <strong>Service code DMRs</strong> can be submitted:

* via the UNECE CEFACT secretariat,
* automatically (as result of new directory [d/e 0054] and/or message type addition [d/e 0065] of which the information has to be provided by the UNECE secretariat to the JWG 1 secretariat one month before the scheduled release of the UN/EDIFACT directory set.

</li>
</ol>
</li>
<li>Submission of Service directory DMRs and Syntax rule DMRs
<ol type="i">
* <strong>Service directory DMRs</strong> and <strong>Syntax rule DMRs</strong> shall be directly submitted to the JWG 1 secretariat.
<li><strong>Service directory DMRs</strong> and <strong>Syntax rule DMRs</strong> shall be forwarded to the JWG 1 secretariat either:

* in electronic form as e-mail text; or
<li>as an attachment to an e-mail in MS Word or RTF format.
and be addressed to: _bernd.boesler@din.de_</li>
<li>Those without an e-mail capability should send their Syntax DMRs by fax or letter to the JWG 1 secretariat at:
Fax: +49 30 2601-42488

Address:

DIN<br />
att. Mr. Boesler<br />
D -- 10772 Berlin<br />
Germany</li>

</li>
</ol>
</li>
</ol>
</li>
</ol>

* Processing (Review) of Syntax DMRs

<ol type="I">
* Syntax DMRs as submitted to the JWG 1 secretariat will be allocated a JWG 1 log number which will be communicated back to the submittor as a confirmation of receipt of the DMR.
* For <strong>Service code DMRs</strong> submitted via the JWG 1 web site, these will be allocated a JWG 1 log number and acknowledged automatically.
<li><strong>Service directory DMRs</strong> and <strong>Syntax rule DMRs</strong> shall be circulated by the JWG 1 secretariat to the experts of JWG 1.
The function of the review shall be to approve the DMR (minor change) or to become a Work Item to be processed by JWG 1. If a DMR is rejected, the reason for the rejection shall be given. Whatever the outcome of the review, the party that submitted the DMR to the JWG 1 shall be notified by the JWG 1 secretariat of the result, including where necessary the reason for a rejection.

DMRs approved as Work Items for JWG 1 shall be processed according to the approved JWG 1 procedures for the progression of its Work Items as set out in the attached Annex.</li>
</ol>

* Publication of approved Syntax DMRs

<ol type="I">
<li>Publication of approved Service code DMRs
Approved <strong>Service code DMRs</strong> shall be applied to the appropriate Service Code List Directories (ISO 9735/V.4 and/or ISO 9735/V.3) and made available as a new directory release at the JWG 1 web site (link:http://www.gefeg.com/jswg" target="_blank[http://www.gefeg.com/jswg]) with the same frequency as that applied to the user UN/EDIFACT Directories (currently two releases per year).

The JWG 1 secretariat shall provide the Service Code Publication Team<a id="refY" href="#Y"><sup>[2]</sup></a>, one month before the next scheduled UN/EDIFACT directory, with all approved <strong>Service code DMRs</strong>. These DMRs shall be applied to the appropriate Service Code List Directories (ISO 9735/V.4 and/or ISO 9735/V.3) and made available as a new directory release at the JWG 1 web site (link:http://www.gefeg.com/jswg" target="_blank[http://www.gefeg.com/jswg]) at the date provided by the JWG 1 secretariat. To ensure proper publication alignment with the UN/EDIFACT Directory set the web host provider, currently GEFEG, will be informed by the JWG 1 secretariat when to make the new web content available to the Public.</li>
<li>Publication of approved Service directory DMRs and Service rule DMRs
Approved Work Items for changing/updating the Service directory and/or the Syntax rules will lead to a new edition of the affected Part(s) of the ISO 9735 standard series and the relevant entries on the JWG 1 web site.</li>
</ol>
<hr align="center" size="2" width="50%" />
&nbsp;

<a id="X" href="#refX">[1]</a>  JSWG = Joint Syntax Working Group = Name of ISO/TC 154/JWG 1<br />
<a id="Y" href="#refY">[2]</a>  Members of the Service Code Publication Team are appointed by the JWG 1 convener and secretariat.

