title: ISO/TC 154
title_html: ISO/TC&nbsp;154

email: open.source@ribose.com

description: >-
  ISO/TC 154: Processes, data elements and documents in commerce, industry and administration

committee:
  chair: shi-yu
  leadership:
    - jianfang-zhang
    - yan-zhang
    - anders-grangard
    - jasmine-chang
    - jim-wilson
    - ronald-tse
    - sue-probert
    # - gregor-roschkowski

baseurl: ""
url: "https://www.isotc154.org"

markdown: kramdown

theme: jekyll-theme-isotc154

excerpt_separator: "// more"

google_analytics:
  id: UA-142331468-1

social:
  links:
    - url: https://twitter.com/ISOTC154
    - url: https://github.com/ISO-TC154
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

footer_nav_items:
  - home
  - about
  - news
  - contact
  - jwg1site

primary_nav_items:
  - news
  - projects
  - standards
  - groups
  - members
  - faq
  - 39th_plenary

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:name/
  standards:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/
  procedures:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /:collection/:name/
  groups:
    output: true
    group-id: :name
    permalink: /:collection/:name/
  members:
    output: true
    member-id: :name
    permalink: /:collection/:name/

defaults:
  - scope:
      path: "faq"
    values:
      layout: faq
  - scope:
      path: ""
      type: standards
    values:
      layout: standard
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: procedures
    values:
      layout: procedures
  - scope:
      path: ""
      type: groups
    values:
      layout: group
  - scope:
      path: ""
      type: posts
    values:
      layout: post

nav:
  about:
    url: /about/
    title: About
  faq:
    url: /faq/
    title: FAQ
  standards:
    url: /standards/
    title: Standards
  projects:
    url: /projects/
    title: Projects
  groups:
    url: /groups/
    title: Groups
  members:
    url: /members/
    title: Members

  39th_plenary:
    url: /39th-plenary/
    title: Plenary
    description: 39th Plenary week
    html_class: featured-event

  home:
    url: /
    title: Home
  news:
    url: /posts/
    title: News
  contact:
    url: /contact
    title: Contact
  jwg1site:
    url: https://www.gefeg.com/jswg/
    title: JWG 1 site

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - node_modules
  - vendor
  - .sass-cache/
