---
permalink: /about/
---
:page-liquid:
= About ISO/TC 154

* Name: Processes, data elements and documents in commerce, industry and administration

* Secretariat: http://www.sac.gov.cn[SAC]
* Secretary: mailto:zhangjf@cnis.gov.cn[Mr Jianfang Zhang]
* Chairperson: Ms Hongru (Judy) Zhu
* ISO Technical Programme Manager: mailto:sarmiento@iso.org[Ms Sonia Sarmiento]
* ISO Editorial Programme Manager: mailto:chen@iso.org[Mrs Yvonne Chen]
* Creation date: 1972

== Scope

International standardization and registration of business, and administration processes and supporting data used for information interchange between and within individual organizations and support for standardization activities in the field of industrial data.

Development and maintenance of application specific meta standards for:

* process specification (in the absence of development by other technical committees);
* data specification with content;
* forms-layout (paper / electronic).

Development and maintenance of standards for:

* process identification (in the absence of development by other technical committees);
* data identification.

Maintenance of the EDIFACT-Syntax.


== Working Groups and Project Teams

{% assign groups = site.groups | sort: "order" %}
{% for group in groups %}
* link:{{ group.url }}[{{ group.title }}]
{% endfor %}
