---
title: About ISO/TC 154
permalink: /about/
layout: page
---
:page-liquid:

= About ISO/TC 154

== Disclaimer

The content on this website is provided by the Technical Committee and
its individual experts. If you have any questions or comments about
this website, or would like to reproduce this content, please contact
the Committee using the link:/contact[Contact] page.


== General

{% assign chair = site.data.members.all['pan-wei'] %}
{% assign secretary = site.data.members.all['jianfang-zhang'] %}
{% assign tpm = site.data.members.all['laura-mathew'] %}
{% assign epm = site.data.members.all['marcela-bonells'] %}

* Name: Processes, data elements and documents in commerce, industry and administration

* Secretariat: http://www.sac.gov.cn[SAC]
* Chairperson: link:{{ chair.url }}[{{ chair.name }}] ({{ chair.affiliation }})
* Committee manager: link:{{ secretary.url }}[{{ secretary.name }}] ({{ secretary.affiliation }})
* ISO Technical Programme Manager: link:{{ tpm.url }}[{{ tpm.name }}] ({{ tpm.affiliation }})
* ISO Editorial Programme Manager: link:{{ epm.url }}[{{ epm.name }}] ({{ epm.affiliation }})
* Creation date: 1972

== Mission

It is the vision of ISO/TC 154 that all parties in the supply and value chain use standardized data exchange to reduce cost in managing the processes in the private and public domain and to foster trade facilitation.

The mission of ISO/TC 154 is both to undertake and to facilitate the development and maintenance of international standards for electronic business in the supply and value chain.

These standards cover data exchange regardless of the media used.

Wherever possible, ISO/TC 154 fosters harmonisation between and within international standards development organizations, particularly through the Memorandum of Understanding between the International Electrotechnical Commission, the International Organization for Standardization, the International Telecommunication Union and the United Nations Economic Commission for Europe concerning standardization in the field of electronic business.

== Scope


International standardization and registration of business, and administration processes and supporting data used for information interchange between and within individual organizations and support for standardization activities in the field of industrial data.

Development and maintenance of application specific meta standards for:

* process specification (in the absence of development by other technical committees);
* data specification with content;
* forms-layout (paper / electronic).

Development and maintenance of standards for:

* process identification (in the absence of development by other technical committees);
* data identification.

Maintenance of the EDIFACT-Syntax.


== Working Groups and Project Teams

{% assign groups = site.groups | sort: "order" %}
{% for group in groups %}
* {% if group.name %}{{ group.name }} — {% endif %} link:{{ group.url }}[{{ group.title }}]
{% endfor %}



== Historic information

== Secretariats

* http://www.sac.gov.cn[SAC] (2014-)

* https://www.nen.nl[NEN] (2008-2013)


== Past Chairs

{% assign person = site.data.members.all['pan-wei'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2026-)

{% assign person = site.data.members.all['shi-yu'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2021-2025)

{% assign person = site.data.members.all['shi-yu'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2021-2025)

{% assign person = site.data.members.all['judy-zhu'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2017-2021)

{% assign person = site.data.members.all['klaus-dieter-naujok'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2011-2016)

{% assign person = site.data.members.all['robert-schubenel'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2008-2010)

{% assign person = site.data.members.all['francois-vuilleumier'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (1998-2008)


== Committee Managers / Secretaries

{% assign person = site.data.members.all['jianfang-zhang'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2014-)

{% assign person = site.data.members.all['francois-vuilleumier'] %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (1998-2008)

