---
title: About ISO/TC 154
permalink: /about/
layout: page
---
:page-liquid:

= About ISO/TC 154

== General

{% assign secretary = site.members | where: "member-id", "jianfang-zhang" | first %}
{% assign chair = site.members | where: "member-id", "judy-zhu" | first %}

* Name: Processes, data elements and documents in commerce, industry and administration

* Secretariat: http://www.sac.gov.cn[SAC]
* Chairperson: link:{{ chair.url }}[{{ chair.name }}] ({{ chair.affiliation }})
* Committee manager: link:{{ secretary.url }}[{{ secretary.name }}] ({{ secretary.affiliation }})
* ISO Technical Programme Manager: mailto:mathew@iso.org[Ms Laura Mathew]
* ISO Editorial Programme Manager: mailto:chen@iso.org[Mrs Yvonne Chen]
* Creation date: 1972

== Scope

International standardization and registration of business, and administration processes and supporting data used for information interchange between and within individual organizations and support for standardization activities in the field of industrial data.

Development and maintenance of application specific meta standards for:

* process specification (in the absence of development by other technical committees);
* data specification with content;
* forms-layout (paper / electronic).

Development and maintenance of standards for:

* process identification (in the absence of development by other technical committees);
* data identification.

Maintenance of the EDIFACT-Syntax.


== Working Groups and Project Teams

{% assign groups = site.groups | sort: "order" %}
{% for group in groups %}
* {% if group.name %}{{ group.name }} — {% endif %} link:{{ group.url }}[{{ group.title }}]
{% endfor %}



== Historic role information

=== Secretariats

* http://www.sac.gov.cn[SAC] (2014-)

* https://www.nen.nl[NEN] (2008-2013)


=== Chairs

{% assign person = site.members | where: "member-id", "judy-zhu" | first %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2017-)

{% assign person = site.members | where: "member-id", "klaus-dieter-naujok" | first %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2011-2016)

{% assign person = site.members | where: "member-id", "robert-schubenel" | first %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2008-2010)

{% assign person = site.members | where: "member-id", "francois-vuilleumier" | first %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (1998-2008)


=== Committee Managers / Secretaries

{% assign person = site.members | where: "member-id", "jianfang-zhang" | first %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (2014-)

{% assign person = site.members | where: "member-id", "francois-vuilleumier" | first %}
* link:{{ person.url }}[{{ person.name }}] ({{ person.affiliation }}) (1998-2008)

