import { defineConfig } from 'astro/config'
import sitemap from '@astrojs/sitemap'
import vue from '@astrojs/vue'
import tailwindcss from '@tailwindcss/vite'
import edoxenHost from './src/integrations/edoxen-host'
import cfg from './edoxen.config'
import legacyRedirects from './src/data/legacy-redirects.json'

export default defineConfig({
  site: 'https://www.isotc154.org',
  integrations: [
    vue(),
    edoxenHost(cfg),
    sitemap(),
  ],
  redirects: {
    // Preserve top-level conceptual redirects
    '/resolutions/': '/decisions/',
    '/resolutions/meetings/': '/meetings/',
    // Per-decision and per-meeting redirects generated by
    // scripts/build-legacy-redirects.mjs from the YAML urn: field.
    ...legacyRedirects,
  },
  vite: {
    plugins: [tailwindcss()],
  },
})
