permalink: /minutes
---
= Minutes Announcements

<article class="blog_wrap  post-6828 post type-post status-publish format-standard hentry category-cat-minutes tag-etsi tag-iso-14533 tag-iso-cs tag-liaison tt-blog-no-feature" id="post-6828">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2017-02-15[CAT Draft Minutes 2017-02-15]</h2>

</div><!-- END post_title -->

== ISO/TC 154 CAT Conference Call
=== 15 February 2017, 15:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), Francois Vuilleumier (FV), Mei-Li Chen (MLC)
Excused::  JianFang Zhang (JFZ), Jasmine Chang (JC), Peter Rybar (PR), Bernd Bösler (BB)

<ol>
* Approval of Agenda – *approved*
* Approval of link:/cat-draft-minutes-2017-02-01[15 February 2017 Meeting Minutes] – *approved*
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

* Henry supports Brian's suggestion that we should create a RA instead of MA
<li>CAT to review the differences, as defined in the latest ISO Directives, in order to come to a ...</li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2017-02-15" rel="bookmark" title="Continue reading CAT Draft Minutes 2017-02-15">
	Continue Reading →</a>
<div class="post_date">
	15

    FEB
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2017-02-15#post-comments[0]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/etsi" rel="tag">ETSI</a>, <a href="/tag/iso-14533" rel="tag">ISO 14533</a>, <a href="/tag/iso-cs" rel="tag">ISO CS</a>, <a href="/tag/liaison" rel="tag[Liaison]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6823 post type-post status-publish format-standard hentry category-cat-minutes tag-etsi tag-iso-14533 tag-iso-cs tag-liaison tag-nwip tag-tc-154 tt-blog-no-feature" id="post-6823">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2017-02-01[CAT Draft Minutes 2017-02-01]</h2>

</div><!-- END post_title -->

<div class="post_content">
== ISO/TC 154 CAT Conference Call
=== 01 February, 15:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Francois Vuilleumier (FV), Peter Rybar (PR)
Excused::  Bernd Bösler (BB), Mei-Li Chen (MLC), Jasmine Chang (JC)

<ol>
* Approval of Agenda – *approved*
* Approval of link:/cat-draft-minutes-2017-01-04[04 January 2017 Meeting Minutes] – *approved*
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

* Currently addressing final comments from Brian regarding the formation of an MA vs RA.

</li>
<li>WG 5 (Representation of dates and times)

* Awaiting DIS Ballot announcement from ISO/CS

</li>
<li>WG 6 (Trusted eCommunication)

<li>External Liaison with ETSI ...</li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2017-02-01" rel="bookmark" title="Continue reading CAT Draft Minutes 2017-02-01">
	Continue Reading →</a>
<div class="post_date">
	1

    FEB
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2017-02-01#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/etsi" rel="tag">ETSI</a>, <a href="/tag/iso-14533" rel="tag">ISO 14533</a>, <a href="/tag/iso-cs" rel="tag">ISO CS</a>, <a href="/tag/liaison" rel="tag">Liaison</a>, <a href="/tag/nwip" rel="tag">NWIP</a>, <a href="/tag/tc-154" rel="tag[TC 154]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6817 post type-post status-publish format-standard hentry category-cat-minutes tag-ballots tag-iso-14533 tag-iso-8601 tag-iso-cs tag-oagi tt-blog-no-feature" id="post-6817">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2017-01-04[CAT Draft Minutes 2017-01-04]</h2>

</div><!-- END post_title -->

<div class="post_content">
== ISO/TC 154 CAT Conference Call
=== 04 January 2017, 15:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), Jasmine Chang (JC), Mei-Li Chen (MLC), Peter Rybar (PR), Bernd Bösler (BB), JianFang Zhang (JFZ)
Excused::  Francois Vuilleumier (FV)

<ol>
* Approval of Agenda – *approved*
* Approval of link:/cat-draft-minutes-2016-12-21[21 December 2016 Meeting Minutes] – *approved*
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

* Awaiting final decision from ISO/CS (Brian)

</li>
<li>WG 5 (Representation of dates and times)

* Out for ballot, closing 2017-03-23

</li>
<li>WG 6 (Trusted eCommunication)

<li>PT1 -- Long term signature profiles

<li>ISO/DIS 14533-3 -- Ballot closed 2016-12-27

<li>PT to ...</li></li></li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2017-01-04" rel="bookmark" title="Continue reading CAT Draft Minutes 2017-01-04">
	Continue Reading →</a>
<div class="post_date">
	4

    JAN
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2017-01-04#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/ballots" rel="tag">Ballots</a>, <a href="/tag/iso-14533" rel="tag">ISO 14533</a>, <a href="/tag/iso-8601" rel="tag">ISO 8601</a>, <a href="/tag/iso-cs" rel="tag">ISO CS</a>, <a href="/tag/oagi" rel="tag[OAGi]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6809 post type-post status-publish format-standard hentry category-cat-minutes tag-ebmou tag-iso-cs tag-moumg tag-nwip tag-resolutions tt-blog-no-feature" id="post-6809">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2016-12-21[CAT Draft Minutes 2016-12-21]</h2>

</div><!-- END post_title -->

<div class="post_content">
== ISO/TC 154 CAT Conference Call
=== 21 December 2016, 15:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), Francois Vuilleumier (FV), Mei-Li Chen (MLC)
Excused::  Jasmine Chang (JC), Bernd Bösler (BB), Peter Rybar (PR), JianFang Zhang (JFZ)

<ol>
* Approval of Agenda – *approved*
* Approval of link:/cat-draft-minutes-2016-11-23[23 November 2016 Meeting Minutes] – *approved*
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

* Awaiting final decision from ISO/CS (Brian)

</li>
<li>WG 5 (Representation of dates and times)

* Awaiting final decision from ISO/CS (Brian)

</li>
<li>WG 6 (Trusted eCommunication)

<li>PT1 -- Long term signature profiles

<li>Awaiting ...</li></li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2016-12-21" rel="bookmark" title="Continue reading CAT Draft Minutes 2016-12-21">
	Continue Reading →</a>
<div class="post_date">
	21

    DEC
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2016-12-21#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/ebmou" rel="tag">ebMoU</a>, <a href="/tag/iso-cs" rel="tag">ISO CS</a>, <a href="/tag/moumg" rel="tag">MoU/MG</a>, <a href="/tag/nwip" rel="tag">NWIP</a>, <a href="/tag/resolutions" rel="tag[Resolutions]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6800 post type-post status-publish format-standard hentry category-cat-minutes tag-ballots tag-iso-14533 tag-iso-8601 tag-moumg tag-semantic-interoperability tt-blog-no-feature" id="post-6800">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2016-11-23[CAT Draft Minutes 2016-11-23]</h2>

</div><!-- END post_title -->

<div class="post_content">
== ISO/TC 154 CAT Conference Call
=== 23 November 2016, 15:00 UTC
*Participants:* Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Francois Vuilleumier (FV), Bernd Bösler (BB), Peter Rybar (PR), Mei-Li Chen (MLC), Jasmine Chang (JC)

<ol>
* Approval of Agenda – *approved*
* Approval of link:/cat-draft-minutes-2016-09-28[28 September 2016 Meeting Minutes] – *approved*
<li>ISO/TC 154 Plenary Recap

* Resolutions -- *reviewed*
* Action items -- *reviewed*

</li>
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

<li>K-DN updated Brian (ISO/CS) on our decision to stick with an MA instead of RA because of the need to process DMRs that ...</li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2016-11-23" rel="bookmark" title="Continue reading CAT Draft Minutes 2016-11-23">
	Continue Reading →</a>
<div class="post_date">
	24

    NOV
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2016-11-23#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/ballots" rel="tag">Ballots</a>, <a href="/tag/iso-14533" rel="tag">ISO 14533</a>, <a href="/tag/iso-8601" rel="tag">ISO 8601</a>, <a href="/tag/moumg" rel="tag">MoU/MG</a>, <a href="/tag/semantic-interoperability" rel="tag[Semantic Interoperability]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6789 post type-post status-publish format-standard hentry category-cat-minutes tag-ballots tag-iso-14533 tag-iso-cs tag-nwip tag-plenary tag-tc-154 tt-blog-no-feature" id="post-6789">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2016-09-28[CAT Draft Minutes 2016-09-28]</h2>

</div><!-- END post_title -->

<div class="post_content">
== ISO/TC 154 CAT Conference Call
=== 14 September 2016, 14:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Francois Vuilleumier (FV)
Excused::  Bernd Bösler (BB), Peter Rybar (PR), Mei-Li Chen (MLC), Jasmine Chang (JC)

<ol>
* Approval of Agenda -- *approved*
* Approval of link:/cat-draft-minutes-2016-09-14[14 September 2016 Meeting Minutes] -- *approved*
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

<li>Feedback from ISO/CS

* _Awaiting comments from ISO/CS_

</li>

</li>
<li>WG 5 (Representation of dates and times)

<li>ISO/CD 8601 Part 1 &amp; 2 Ballot Results

* *Nothing to report since last CAT meeting*

</li>

</li>
<li>WG 6 (Trusted eCommunication)

<li>PT1 -- Long ...</li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2016-09-28" rel="bookmark" title="Continue reading CAT Draft Minutes 2016-09-28">
	Continue Reading →</a>
<div class="post_date">
	28

    SEP
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2016-09-28#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/ballots" rel="tag">Ballots</a>, <a href="/tag/iso-14533" rel="tag">ISO 14533</a>, <a href="/tag/iso-cs" rel="tag">ISO CS</a>, <a href="/tag/nwip" rel="tag">NWIP</a>, <a href="/tag/plenary" rel="tag">Plenary</a>, <a href="/tag/tc-154" rel="tag[TC 154]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6784 post type-post status-publish format-standard hentry category-cat-minutes tag-ballots tag-iso-8601 tag-odif tag-plenary tag-semantic-interoperability tt-blog-no-feature" id="post-6784">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2016-09-14[CAT Draft Minutes 2016-09-14]</h2>

</div><!-- END post_title -->

<div class="post_content">
== ISO/TC 154 CAT Conference Call
=== 14 September 2016, 14:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Francois Vuilleumier (FV), Mei-Li Chen (MLC)
Excused::  Bernd Bösler (BB), Jasmine Chang (JC), Peter Rybar (PR)

<ol>
* Approval of Agenda -- *approved*
* Approval of link:/cat-draft-minutes-2016-08-31[31 August 2016 Meeting Minutes] -- *approved*
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

<li>Feedback from ISO/CS

* _Awaiting comments from ISO/CS_

</li>

</li>
<li>WG 5 (Representation of dates and times)

<li>ISO/CD 8601 Part 1 &amp; 2 Ballot Results

* _Approved with no negative vote or required technical corrections (comments)_

</li>
<li>Next step

<li>_Preparing for ..._</li></li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2016-09-14" rel="bookmark" title="Continue reading CAT Draft Minutes 2016-09-14">
	Continue Reading →</a>
<div class="post_date">
	15

    SEP
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2016-09-14#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/ballots" rel="tag">Ballots</a>, <a href="/tag/iso-8601" rel="tag">ISO 8601</a>, <a href="/tag/odif" rel="tag">ODIF</a>, <a href="/tag/plenary" rel="tag">Plenary</a>, <a href="/tag/semantic-interoperability" rel="tag[Semantic Interoperability]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6774 post type-post status-publish format-standard hentry category-cat-minutes tag-afact tag-ballots tag-edifact tag-semantic-interoperability tag-wco tt-blog-no-feature" id="post-6774">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2016-08-31[CAT Draft Minutes 2016–08–31]</h2>

</div><!-- END post_title -->

<div class="post_content">
<h3 id="isotc154catconferencecall">ISO/TC 154 CAT Conference Call</h3>
== 31 August 2016, 14:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Francois Vuilleumier (FV), Mei-Li Chen (MLC)
Excused::  Bernd Bösler (BB), Jasmine Chang (JC), Peter Rybar (PR)

<ol>
* Approval of Agenda -- *approved* with addition under 8. Other business
* Approval of link:/cat-draft-minutes-2016-08-17[17 August 2016 Meeting Minutes] -- *approved*
<li>Working Group and Project Team Updates

<li>JWG1/MA (EDIFACT Syntax)

* Feedback from ISO/CS -- Nothing to report

</li>
<li>WG 5 (Representation of dates and times)

<li>ISO 8601 Part 1 &amp; 2 update

* Out for CD ballot closing 2016–09–03

</li>

</li>
<li>WG 6 (Trusted eCommunication)

<li>PT1 -- Long ...</li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2016-08-31" rel="bookmark" title="Continue reading CAT Draft Minutes 2016–08–31">
	Continue Reading →</a>
<div class="post_date">
	31

    AUG
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2016-08-31#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/afact" rel="tag">AFACT</a>, <a href="/tag/ballots" rel="tag">Ballots</a>, <a href="/tag/edifact" rel="tag">EDIFACT</a>, <a href="/tag/semantic-interoperability" rel="tag">Semantic Interoperability</a>, <a href="/tag/wco" rel="tag[WCO]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6769 post type-post status-publish format-standard hentry category-cat-minutes tag-ballots tag-iso-8601 tag-iso-cs tag-oagi tag-plenary tt-blog-no-feature" id="post-6769">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2016-08-17[CAT Draft Minutes 2016-08-17]</h2>

</div><!-- END post_title -->

<div class="post_content">
<h3 id="isotc154catconferencecall">ISO/TC 154 CAT Conference Call</h3>
== 17 August 2016, 14:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Bernd Bösler (BB), Jasmine Chang (JC)
Excused::  Francois Vuilleumier (FV), Mei-Li Chen (MLC), Peter Rybar (PR)

<ol>
* Approval of Agenda -- *approved*
* Approval of link:/cat-draft-minutes-2016-08-03[03 August 2016 Meeting Minutes] -- *approved*
<li>Working Group and Project Team Updates

* JWG1/MA (EDIFACT Syntax) -- Nothing to report
<li>WG 5 (Representation of dates and times)

<li>ISO 8601 Part 1 &amp; 2 update

* Out for CD ballot closing 2016–09–03

</li>

</li>
<li>WG 6 (Trusted eCommunication)

<li>PT1 -- Long term signature profiles for PDF advanced electronic ...</li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2016-08-17" rel="bookmark" title="Continue reading CAT Draft Minutes 2016-08-17">
	Continue Reading →</a>
<div class="post_date">
	17

    AUG
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2016-08-17#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/ballots" rel="tag">Ballots</a>, <a href="/tag/iso-8601" rel="tag">ISO 8601</a>, <a href="/tag/iso-cs" rel="tag">ISO CS</a>, <a href="/tag/oagi" rel="tag">OAGi</a>, <a href="/tag/plenary" rel="tag[Plenary]


        </div><!-- END post_footer -->
</article><!-- END blog_wrap -->
<article class="blog_wrap  post-6765 post type-post status-publish format-standard hentry category-cat-minutes tag-iso-14533 tag-iso-8601 tag-nwip tag-oagi tag-plenary tt-blog-no-feature" id="post-6765">
<div class="post_title">

<h2 class="entry-title">link:/cat-draft-minutes-2016-08-03[CAT Draft Minutes 2016-08-03]</h2>

</div><!-- END post_title -->

<div class="post_content">
<h3 id="isotc154catconferencecall">ISO/TC 154 CAT Conference Call</h3>
== 03 August<a id="MMDHTMLSCROLLPOINT"></a> 2016, 14:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Bernd Bösler (BB), Jasmine Chang (JC), Peter Rybar (PR)
Excused::  Francois Vuilleumier (FV), Mei-Li Chen (MLC)

<ol>
* Approval of Agenda -- *approved* with addition of “ODIF Update” under item 8.
* Approval of link:/cat-draft-minutes-2016-07-20[20 July 2016 Meeting Minutes] -- *approved*
<li>Working Group and Project Team Updates

* JWG1/MA (EDIFACT Syntax) -- Nothing to report
<li>WG 5 (Representation of dates and times)

<li>ISO 8601 Part 1 &amp; 2 update

* Out for CD ballot closing 2016–09–03

</li>

</li>
<li>WG 6 (Trusted eCommunication)

<li>PT1 -- Long ...</li></li></li></ol><a class="ka_button small_button small_black" href="/cat-draft-minutes-2016-08-03" rel="bookmark" title="Continue reading CAT Draft Minutes 2016-08-03">
	Continue Reading →</a>
<div class="post_date">
	3

    AUG
</div><!-- END post_date -->

<div class="post_comments">
	link:/cat-draft-minutes-2016-08-03#post-comments[1]
</div><!-- END post_comments -->


</div><!-- END post_content -->

<div class="post_footer">
            <p class="post_cats">* link:/category/news/cat-minutes[CAT Minutes]


                <p class="post_tags">link:/tag/iso-14533" rel="tag">ISO 14533</a>, <a href="/tag/iso-8601" rel="tag">ISO 8601</a>, <a href="/tag/nwip" rel="tag">NWIP</a>, <a href="/tag/oagi" rel="tag">OAGi</a>, <a href="/tag/plenary" rel="tag[Plenary]


<aside role="complementary" id="sidebar" class="sidebar_blog">

== Recent Posts

* link:/cat-draft-minutes-2017-02-15[CAT Draft Minutes 2017-02-15]
* link:/cat-draft-minutes-2017-02-01[CAT Draft Minutes 2017-02-01]
* link:/cat-draft-minutes-2017-01-04[CAT Draft Minutes 2017-01-04]
* link:/cat-draft-minutes-2016-12-21[CAT Draft Minutes 2016-12-21]
* link:/cat-draft-minutes-2016-11-23[CAT Draft Minutes 2016-11-23]

== Archives

* link:/2017/02[February 2017]
* link:/2017/01[January 2017]
* link:/2016/12[December 2016]
* link:/2016/11[November 2016]
* link:/2016/09[September 2016]
* link:/2016/08[August 2016]
* link:/2016/07[July 2016]
* link:/2016/06[June 2016]
* link:/2016/05[May 2016]
* link:/2016/04[April 2016]
* link:/2016/03[March 2016]
* link:/2016/02[February 2016]
* link:/2016/01[January 2016]
* link:/2015/12[December 2015]
* link:/2015/11[November 2015]
* link:/2015/10[October 2015]
* link:/2015/09[September 2015]
* link:/2015/08[August 2015]
* link:/2015/07[July 2015]
* link:/2015/06[June 2015]
* link:/2015/05[May 2015]
* link:/2015/04[April 2015]
* link:/2015/03[March 2015]
* link:/2015/02[February 2015]
* link:/2015/01[January 2015]
* link:/2014/12[December 2014]
* link:/2014/11[November 2014]
* link:/2014/10[October 2014]
* link:/2014/09[September 2014]
* link:/2014/08[August 2014]
* link:/2014/07[July 2014]
* link:/2014/06[June 2014]
* link:/2014/05[May 2014]
* link:/2014/04[April 2014]
* link:/2014/03[March 2014]
* link:/2014/02[February 2014]
* link:/2014/01[January 2014]
* link:/2013/12[December 2013]
* link:/2013/10[October 2013]
* link:/2013/09[September 2013]
* link:/2013/08[August 2013]
* link:/2013/07[July 2013]
* link:/2013/06[June 2013]
* link:/2013/05[May 2013]
* link:/2013/04[April 2013]
* link:/2013/03[March 2013]
* link:/2013/02[February 2013]
* link:/2013/01[January 2013]
* link:/2012/12[December 2012]
* link:/2012/11[November 2012]
* link:/2012/10[October 2012]
* link:/2012/09[September 2012]
* link:/2012/08[August 2012]
* link:/2012/07[July 2012]
* link:/2012/06[June 2012]
* link:/2012/05[May 2012]
* link:/2012/04[April 2012]
* link:/2012/03[March 2012]
* link:/2012/02[February 2012]
* link:/2012/01[January 2012]
* link:/2011/12[December 2011]
* link:/2011/11[November 2011]
* link:/2011/10[October 2011]
* link:/2011/09[September 2011]
* link:/2011/06[June 2011]

== Categories
* link:/category/news/announcement[Announcement]

* link:/category/news/call-for-experts[Call for Experts]

* link:/category/news/cat-minutes[CAT Minutes]

* link:/category/news/chairman-message[Chairman Message]

* link:/category/news/iso-press-release[ISO Press Release]

* link:/category/news[News]

* link:/category/news/plenary-minutes[Plenary Minutes]

* link:/category/news/reports[Reports]

== Tags

* link:/tag/afact[AFACT]
* link:/tag/ballots[Ballots]
* link:/tag/cat[CAT]
* link:/tag/ccts[CCTS]
* link:/tag/e-invoice[e-invoice]
* link:/tag/ebmou[ebMoU]
* link:/tag/ebxml[ebXML]
* link:/tag/edifact[EDIFACT]
* link:/tag/etsi[ETSI]
* link:/tag/for-information[For Information]
* link:/tag/imo[IMO]
* link:/tag/iso-6422[ISO 6422]
* link:/tag/iso-8439[ISO 8439]
* link:/tag/iso-8440[ISO 8440]
* link:/tag/iso-8601[ISO 8601]
* link:/tag/iso-9735[ISO 9735]
* link:/tag/iso-14533[ISO 14533]
* link:/tag/iso-15000[ISO 15000]
* link:/tag/iso-17469[ISO 17469]
* link:/tag/iso-20625[ISO 20625]
* link:/tag/iso-28005[ISO 28005]
* link:/tag/iso-cs[ISO CS]
* link:/tag/layout-key[Layout Key]
* link:/tag/liaison[Liaison]
* link:/tag/moumg[MoU/MG]
* link:/tag/nwip[NWIP]
* link:/tag/oagi[OAGi]
* link:/tag/oasis[OASIS]
* link:/tag/odif[ODIF]
* link:/tag/plenary[Plenary]
* link:/tag/poc[PoC]
* link:/tag/project-portal[Project Portal]
* link:/tag/recommendation-37[Recommendation 37]
* link:/tag/resolutions[Resolutions]
* link:/tag/sdmx[SDMX]
* link:/tag/semantic-interoperability[Semantic Interoperability]
* link:/tag/tc-8[TC 8]
* link:/tag/tc-154[TC 154]
* link:/tag/tc-171[TC 171]
* link:/tag/tc-211[TC 211]
* link:/tag/ubl[UBL]
* link:/tag/uncefact[UN/CEFACT]
* link:/tag/unece[UNECE]
* link:/tag/wco[WCO]
