allowBuilds:
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - esbuild
  - sharp
shamefullyHoist: false
strictPeerDependencies: false

overrides:
  brace-expansion: ">=2.1.4"
  fast-uri: ">=3.1.6"
  js-yaml: "~4.3.1"
  nanoid: ">=3.3.18"
  postcss: ">=8.5.23"
