permalink: /projects
---
= Projects

<nav role="navigation">

<li id="item-4937"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us">*About Us*<span class="navi-description[Who we are</span>]

	<li id="item-5004"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us/jwg1[JWG 1 – EDIFACT Syntax]
	
		link:/about_us/jwg1/sdmr[Syntax DMR Procedures]
	
</li>
	link:/about_us/wg3[WG 3 – CCTS]
	link:/about_us/wg4[WG 4 – eLK]
	link:/about_us/cat[CAT -- Chairman's Advisory Team]
	<li id="item-5034"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us/ma[TDED Maintenance Agency]
	
		link:/about_us/ma/membership-of-the-tded-maintenance-agency[Membership of the TDED MA]
		link:/about_us/ma/ma_links[Relevant links to TDED MA folders/files]
	
</li>

</li>
<li id="item-4922"  class=" menu-item menu-item-type-post_type menu-item-object-page  menu-item-has-children">link:/projects">*Projects*<span class="navi-description[What we do</span>]

	link:/projects/iso-np-6422-2[ISO NP 6422-2]
	link:/projects/iso-np-14533[ISO NP 14533]
	link:/projects/iso-pwi-tr-6422-3[ISO PWI TR 6422-3]
	link:/projects/iso-np-9735-10[ISO NP 9735-10]
	link:/projects/iso-np-15000-5[ISO NP 15000-5]
	link:/projects/iso-np-17369[ISO NP 17369]

</li>
<li id="item-4912"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/standards">*Standards*<span class="navi-description[Our output</span>]

	link:/standards/iso-6422-12010[ISO 6422-1:2010]
	link:/standards/iso-73722005[ISO 7372:2005]
	link:/standards/iso-84391990[ISO 8439:1990]
	link:/standards/iso-84401986[ISO 8440:1986]
	link:/standards/iso-86012004[ISO 8601:2004]
	link:/standards/iso-97351988[ISO 9735:1988]
	link:/standards/iso-97351988amd-11992[ISO 9735:1988/Amd 1:1992]
	link:/standards/iso-9735-12002[ISO 9735-1:2002]
	link:/standards/iso-9735-22002[ISO 9735-2:2002]
	link:/standards/iso-9735-32002[ISO 9735-3:2002]
	link:/standards/iso-9735-42002[ISO 9735-4:2002]
	link:/standards/iso-9735-52002[ISO 9735-5:2002]
	link:/standards/iso-9735-62002[ISO 9735-6:2002]
	link:/standards/iso-9735-72002[ISO 9735-7:2002]
	link:/standards/iso-9735-82002[ISO 9735-8:2002]
	link:/standards/iso-9735-92002[ISO 9735-9:2002]
	link:/standards/iso-9735-102002[ISO 9735-10:2002]
	link:/standards/isots-15000-12004[ISO/TS 15000-1:2004]
	link:/standards/isots-15000-22004[ISO/TS 15000-2:2004]
	link:/standards/isots-15000-32004[ISO/TS 15000-3:2004]
	link:/standards/isots-15000-42004[ISO/TS 15000-4:2004]
	link:/standards/isots-15000-52005[ISO/TS 15000-5:2005]
	link:/standards/isots-173692005[ISO/TS 17369:2005]
	link:/standards/isots-206252002[ISO/TS 20625:2002]

</li>
link:/minutes">*Minutes*<span class="navi-description[Announcements</span>]
link:/faq">*FAQ*<span class="navi-description[Your questions</span>]
link:/isotc-154-2016-anual-meeting-details">*Meetings*<span class="navi-description[2016 Meetings</span>]

</nav>
</div><!-- END header-area -->
</div><!-- END header-overlay -->
</div><!-- END header-holder -->
</header><!-- END header -->


<div id="main" class="tt-slider-">


<div class="main-area">

<nav role="navigation" id="sub_nav" class="nav_right_sub_nav">







	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-6422-2[ISO NP 6422-2]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-14533[ISO NP 14533]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-pwi-tr-6422-3[ISO PWI TR 6422-3]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-9735-10[ISO NP 9735-10]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-15000-5[ISO NP 15000-5]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-17369[ISO NP 17369]</li>

</nav><!-- END sub_nav -->


<h2 id="current_projects">Current projects</h2>


<li><a title="ISO NP 6422-2 Layout key for trade documents — Part 2: Electronic documents" href="/projects/iso-np-6422-2">ISO NP 6422-2</a><br />
Layout key for trade documents — Part 2: Electronic documents<br />
NOTE: This WI has been canceled and instead the new PWI TR 6422-3 has been created. (see below)</li>
<li><a title="ISO NP 14533 Long Term Signature profiles for EDI Data and Electronic Documents" href="/projects/iso-np-14533">ISO NP 14533</a><br />
Long Term Signature profiles for EDI Data and Electronic Documents</li>


NOTE: This WI has been modified to create two parts:



<li>ISO/DIS 14533-1<br />
Processes, data elements and documents in commerce, industry and administration — Long term signature profiles — Part 1: Long term signature profiles for CMS Advanced Electronic Signatures (CAdES)</li>
<li>ISO/DIS 14533-2<br />
Processes, data elements and documents in commerce, industry and administration — Long term signature profiles — Part 2: Long term signature profiles for XML Advanced Electronic Signatures (XAdES)</li>


<h2 id="new_work_items_in_progress_to_be_started_call_for_experts">New Work Items in progress to be started (Call for Experts)</h2>

* <a title="ISO PWI TR 6422-3 Analysis for user requirements for layout key of trade documents — Part 3:" href="/projects/iso-pwi-tr-6422-3">ISO PWI TR 6422-3</a> -- Analysis for user requirements for layout key of trade documents
* Revision of <a title="ISO 9735-10 Rev" href="/projects/iso-9735-10-rev">ISO 9735-10</a> -- EDIFACT – Syntax service directories
* Revision of <a title="ISO NP 15000-5 ebXML – Part 5: ebCCTS" href="/projects/iso-np-15000-5">ISO/TS 15000-5</a> -- ebCCTS, as an International Standard
* Revision of <a title="ISO NP 17369 Statistical data and metadata exchange (SDMX)" href="/projects/iso-np-17369-statistical-data-and-metadata-exchange-sdmx">ISO/TS 17369</a> – Statistical data and metadata exchange (SDMX), as an International Standard (IS)

