permalink: /projects
---
= Projects

<nav role="navigation">
<ul id="menu-main-nav" class="sf-menu">
<li id="item-4937"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us"><span>*About Us*<span class="navi-description[Who we are</span></span>]
<ul class="sub-menu">
	<li id="item-5004"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us/jwg1[<span>JWG 1 – EDIFACT Syntax</span>]
	<ul class="sub-menu">
		<li id="item-5215"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/jwg1/sdmr[<span>Syntax DMR Procedures</span>]</li>
	</ul>
</li>
	<li id="item-5007"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/wg3[<span>WG 3 – CCTS</span>]</li>
	<li id="item-5013"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/wg4[<span>WG 4 – eLK</span>]</li>
	<li id="item-5252"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/cat[<span>CAT -- Chairman's Advisory Team</span>]</li>
	<li id="item-5034"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/about_us/ma[<span>TDED Maintenance Agency</span>]
	<ul class="sub-menu">
		<li id="item-5581"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/ma/membership-of-the-tded-maintenance-agency[<span>Membership of the TDED MA</span>]</li>
		<li id="item-5585"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/about_us/ma/ma_links[<span>Relevant links to TDED MA folders/files</span>]</li>
	</ul>
</li>
</ul>
</li>
<li id="item-4922"  class=" menu-item menu-item-type-post_type menu-item-object-page  menu-item-has-children">link:/projects"><span>*Projects*<span class="navi-description[What we do</span></span>]
<ul class="sub-menu">
	<li id="item-5146"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-6422-2[<span>ISO NP 6422-2</span>]</li>
	<li id="item-5149"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-14533[<span>ISO NP 14533</span>]</li>
	<li id="item-5136"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-pwi-tr-6422-3[<span>ISO PWI TR 6422-3</span>]</li>
	<li id="item-5173"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-9735-10[<span>ISO NP 9735-10</span>]</li>
	<li id="item-5180"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-15000-5[<span>ISO NP 15000-5</span>]</li>
	<li id="item-5184"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-17369[<span>ISO NP 17369</span>]</li>
</ul>
</li>
<li id="item-4912"  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">link:/standards"><span>*Standards*<span class="navi-description[Our output</span></span>]
<ul class="sub-menu">
	<li id="item-5127"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-6422-12010[<span>ISO 6422-1:2010</span>]</li>
	<li id="item-5131"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-73722005[<span>ISO 7372:2005</span>]</li>
	<li id="item-5284"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-84391990[<span>ISO 8439:1990</span>]</li>
	<li id="item-5283"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-84401986[<span>ISO 8440:1986</span>]</li>
	<li id="item-5282"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-86012004[<span>ISO 8601:2004</span>]</li>
	<li id="item-5323"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-97351988[<span>ISO 9735:1988</span>]</li>
	<li id="item-5322"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-97351988amd-11992[<span>ISO 9735:1988/Amd 1:1992</span>]</li>
	<li id="item-5326"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-12002[<span>ISO 9735-1:2002</span>]</li>
	<li id="item-5325"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-22002[<span>ISO 9735-2:2002</span>]</li>
	<li id="item-5370"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-32002[<span>ISO 9735-3:2002</span>]</li>
	<li id="item-5369"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-42002[<span>ISO 9735-4:2002</span>]</li>
	<li id="item-5368"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-52002[<span>ISO 9735-5:2002</span>]</li>
	<li id="item-5367"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-62002[<span>ISO 9735-6:2002</span>]</li>
	<li id="item-5366"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-72002[<span>ISO 9735-7:2002</span>]</li>
	<li id="item-5365"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-82002[<span>ISO 9735-8:2002</span>]</li>
	<li id="item-5364"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-92002[<span>ISO 9735-9:2002</span>]</li>
	<li id="item-5363"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/iso-9735-102002[<span>ISO 9735-10:2002</span>]</li>
	<li id="item-5392"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/isots-15000-12004[<span>ISO/TS 15000-1:2004</span>]</li>
	<li id="item-5391"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/isots-15000-22004[<span>ISO/TS 15000-2:2004</span>]</li>
	<li id="item-5390"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/isots-15000-32004[<span>ISO/TS 15000-3:2004</span>]</li>
	<li id="item-5389"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/isots-15000-42004[<span>ISO/TS 15000-4:2004</span>]</li>
	<li id="item-5388"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/isots-15000-52005[<span>ISO/TS 15000-5:2005</span>]</li>
	<li id="item-5387"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/isots-173692005[<span>ISO/TS 17369:2005</span>]</li>
	<li id="item-5386"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/standards/isots-206252002[<span>ISO/TS 20625:2002</span>]</li>
</ul>
</li>
<li id="item-4909"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/minutes"><span>*Minutes*<span class="navi-description[Announcements</span></span>]</li>
<li id="item-4983"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/faq"><span>*FAQ*<span class="navi-description[Your questions</span></span>]</li>
<li id="item-6479"  class=" menu-item menu-item-type-post_type menu-item-object-page">link:/isotc-154-2016-anual-meeting-details"><span>*Meetings*<span class="navi-description[2016 Meetings</span></span>]</li>
</ul>
</nav>
</div><!-- END header-area -->
</div><!-- END header-overlay -->
</div><!-- END header-holder -->
</header><!-- END header -->


<div id="main" class="tt-slider-">


<div class="main-area">

<nav role="navigation" id="sub_nav" class="nav_right_sub_nav">

<ul class="sub-menu">


</ul>

<ul class="sub-menu">
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-6422-2[ISO NP 6422-2]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-14533[ISO NP 14533]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-pwi-tr-6422-3[ISO PWI TR 6422-3]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-9735-10[ISO NP 9735-10]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-15000-5[ISO NP 15000-5]</li>
	<li class="menu-item menu-item-type-post_type menu-item-object-page">link:/projects/iso-np-17369[ISO NP 17369]</li>
</ul>
</nav><!-- END sub_nav -->


<h2 id="current_projects">Current projects</h2>
<ul>
<ul>
<li><a title="ISO NP 6422-2 Layout key for trade documents — Part 2: Electronic documents" href="/projects/iso-np-6422-2">ISO NP 6422-2</a><br />
Layout key for trade documents — Part 2: Electronic documents<br />
NOTE: This WI has been canceled and instead the new PWI TR 6422-3 has been created. (see below)</li>
<li><a title="ISO NP 14533 Long Term Signature profiles for EDI Data and Electronic Documents" href="/projects/iso-np-14533">ISO NP 14533</a><br />
Long Term Signature profiles for EDI Data and Electronic Documents</li>
</ul>
</ul>
NOTE: This WI has been modified to create two parts:

<ul>
<ul>
<li>ISO/DIS 14533-1<br />
Processes, data elements and documents in commerce, industry and administration — Long term signature profiles — Part 1: Long term signature profiles for CMS Advanced Electronic Signatures (CAdES)</li>
<li>ISO/DIS 14533-2<br />
Processes, data elements and documents in commerce, industry and administration — Long term signature profiles — Part 2: Long term signature profiles for XML Advanced Electronic Signatures (XAdES)</li>
</ul>
</ul>
<h2 id="new_work_items_in_progress_to_be_started_call_for_experts">New Work Items in progress to be started (Call for Experts)</h2>
<ul>
<li><a title="ISO PWI TR 6422-3 Analysis for user requirements for layout key of trade documents — Part 3:" href="/projects/iso-pwi-tr-6422-3">ISO PWI TR 6422-3</a> -- Analysis for user requirements for layout key of trade documents</li>
<li>Revision of <a title="ISO 9735-10 Rev" href="/projects/iso-9735-10-rev">ISO 9735-10</a> -- EDIFACT – Syntax service directories</li>
<li>Revision of <a title="ISO NP 15000-5 ebXML – Part 5: ebCCTS" href="/projects/iso-np-15000-5">ISO/TS 15000-5</a> -- ebCCTS, as an International Standard</li>
<li>Revision of <a title="ISO NP 17369 Statistical data and metadata exchange (SDMX)" href="/projects/iso-np-17369-statistical-data-and-metadata-exchange-sdmx">ISO/TS 17369</a> – Statistical data and metadata exchange (SDMX), as an International Standard (IS)</li>
</ul>
