= ISO/TC 154 Resources site: www.isotc154.org

image:https://travis-ci.com/iso-tc154/www.isotc154.org.svg?branch=master[
	Build Status, link="https://travis-ci.com/iso-tc154/www.isotc154.org"]

== Introduction

The ISO/TC 154 Resources site is used to publish resources and files
relating to or referenced by ISO/TC 154 standards.

This repository is used to build and deploy the
https://www.isotc154.org site.

This repository is jointly managed by ISO/TC 154 and Ribose.


== Content management

* **Excerpt separator**, where allowed, should be in this form: `// more`.
  This has been specified in `_config.yml` to match AsciiDoc’s comment syntax.
* If title, name, etc. is required by YAML frontmatter,
  **avoid** specifying main title in content with AsciiDoc’s equal sign
  to avoid relying on implicit behavior and order of interpretation.
  Start document contents with text, or second-level heading (AsciiDoc’s double equal sign).

Pay attention to **style recommendations** below.

=== Members

Each document in the members collection is expected to have the following
frontmatter:

[source,yaml]
--
member-id: name-with-dashes
name: Full Name
role: role_with_underscores
affiliation: Organization, country (freeform)

picture: file-name-with.extension
# Picture is optional.
# Filename must be relative to /assets/images/members/ directory.
--

=== Groups

Each document expects the following frontmatter YAML structure:

[source,yaml]
--
id: wg3
# Required. Shorthand for the group. Used in URLs, for example.

name: WG 3
# Optional, but good to have. Human-readable group identifier.

title: UN TDED — ISO 7372 Joint Maintenance Agency (JMA)
# Required. Full group name, excluding identifier specified under name.

order: 9
# Determines order in group listing/index.

featured_on_home: true
# Determines whether the group is selected to be shown on site index page.
--

For groups selected to be featured on site index,
content after frontmatter MUST specify excerpt separator.
Text before excerpt separator will be shown on project index,
and therefore should be focusing on group origin and purpose.
This initial part should be well-written and avoid complex formatting
(such as images), since it can’t be accommodated by site layout.

=== Projects

Each document requires following frontmatter YAML structure:

[source,yaml]
--
id: iso-6422-2
# Project ID with dashes

name: ISO/NP 6422-2
# Human-readable project ID

title: "Layout key for trade documents -- Part 2: Electronic documents"
# Descriptive project title, excluding the ID specified under name

status: current
# Either “new” or “current”
--

The content following frontmatter may specify excerpt separator.
Content before excerpt separator will be shown on project index.

=== Standards

Each document requires following frontmatter YAML structure:

[source,yaml]
--
name: ISO/TS 15000-4:2004
# Full standard reference / ID

type: TS
# “TS” or “international”

title: "Electronic business eXtensible Markup Language (ebXML) -- Part 4: Registry services specification (ebRS)"
# Full readable standard title, excluding the ID specified under name
--

=== Minutes

DEPRECATED (https://github.com/iso-tc154/www.isotc154.org/issues/12)

==== YAML frontmatter

Requires YAML in following format:

[source,yaml]
--
# *** Below are required.

title: ISO/TC 154 CAT Meeting Minutes YYYY-MM-DD
permalink: "/minutes/YYYY-MM-DD/"
date: YYYY-MM-DDTHH:MM:SSZ

# *** Below are prescribed by layout; omit at own risk, pages may look incorrect or broken.

subtitle: ISO/TC 154 CAT Conference Call

cat: CAT Minutes
# Primary category

tags:  [tag 1, tag 2]
# Tag names may contain slashes and regular whitespaces.
# Exclude primary category here.

participants:
  - Name 1 <string>
  - Name 2 <string>
excused:
  - Name 3 <string>
  - Name 4 <string>

# *** Below are optional.

scheduled_time: Date/time, possibly with range <string>
secretariat: Name 5 <string>
chair: Name 6 <string>

excerpt: >-
  <p>
    Agenda: approved.
  </p>
# Allowed HTML tags: <a>, <p>, <ul>, <ol> <li>.
--

Following YAML expected agenda notes, beginning with second-level heading
(AsciiDoc’s double equal sign).

==== Action point summary

Apply `.action-points` class to ongoing action point summary tables.

Example markup:

[source,asciidoc]
--
// …

== Ongoing action point summary

[.action-points]
|===
|No| Action points| Owner| Deadline

|20
|WG convenors send the draft of WG meeting agenda to secretary and then upload to the WG website seperatly.
|@ISO7372MA Sue
|2018/10/07

// other table rows…
--

=== Events

NOTE: Implementation in progress.

Enter event data under _data/events.yaml, under a key that is used as global event ID.

Use existing 39th plenary week as a general format spec.

==== Navigation

Each navigation item’s details are contained under `<event ID>.nav.<nav item ID>`.

Each item can define sub-items by listing their IDs `<event ID>.nav.<nav item ID>.items`.

Top-level event navigation item order is defined under `<event ID>.primary_nav.items`,
again as a list of nav item IDs.

IMPORTANT: `<event ID>.primary_nav.items` MUST come in the order of
(1) arrival-related orientation info;
(2) event programme,
(3) sponsors,
(4) any other sections (usually none).

==== Notices for event attendees

If you need to post a notice, alert or news entry only relevant to event attendees,
do **not** create a general news article.

Instead, add an array item in `events.yaml` data structure
under ``<event ID>.notices``. Each item under notices array should look like following:

[source,yaml]
====
title: Booking deadline is approaching
# A 3-6 word string.

html_class: warning
# HTML class can attach styling to the notice
# thorugh events.scss.

icon: exclamation-triangle
# Icon from FontAwesome 5 free solid style selection.
# Could be used to represent the type of notice.

content: >-
  If you plan to stay at the official conference hotel,
  make sure to make your reservation by **July 8th**.
# AsciiDoc-formatted string, keep up to 10-20 words.
# For further content, link to a separate page
# using read_more_action.
# You may want to include that page under event nav.

read_more_action:
  title: Read more about accommodation
  link: /39th-plenary/arrival/accommodation/
====

It may be worth to notify attendees through other means as well.

=== News and articles (aka posts)

A document in posts collection is expected to contain regular Jekyll post frontmatter
(date, title); **no** permalink.

Posts may also specify “see also” items in frontmatter:

[source,yaml]
====
see_also:
- link: https://www.iso.org/news/ref2379.html
  title: ISO press release
====

Posts should specify sensible excerpts. Separate excerpt with excerpt separator;
ensure content before the separator does not contain special formatting.
Excerpts are shown in certain cases, e.g. on post index for latest featured post.


== Style recommendations

=== Awkward linebreaks

When specifying titles and similar strings,
reduce the potential for awkward linebreaks in end site layout
by using non-breaking space `+&nbsp;+` instead of normal whitespace.

Linebreaks are considered “awkward” where newline happen after
e.g. hanging prepositions, particles and articles.
Example of awkward linebreak in group name, how it would look on a rendered page
if viewport is too narrow to fit the name in one line:

  JWG 1 (with
  UNECE)

The way to solve that is to give hints to the browser as to where the line
shouldn’t be broken if possible:

[source,yaml]
--
---
id: jwg1
name: JWG&nbsp;1 (with&nbsp;UNECE)
---
--

With that solution, browser will break the line in a way that is less disruptive
to the reader:

  JWG 1
  (with UNECE)

(Where these values appear in page’s meta title,
HTML entities such as `+&nbsp;+` are stripped.)


== Building the site

////
# initializes/fetches the submodules (not used here)
# make update-init update-modules
////

[source,sh]
----
# removes site artifacts
make clean

# makes _site
make all
----

