---
permalink: "/minutes/2016-04-27"/
date: "27 Apr 2016 22:27:00 +0000"
category: CAT Minutes
category: CAT
category: ISO 14533
category: ISO 8601
category: Plenary
---
= CAT Draft Minutes 2016-04-27

== ISO/TC154 CAT Conference Call, 27 April 2016, 14:00 UTC
Participants::  Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Mei-Li Chen (MLC), Peter Rybar (PR), Jasmine Chang (JC), Francois Vuilleumier (FV), Bernd Bösler (BB)
Excused::  Sue Probert (SP)

== Approval of Agenda  -- *approved*
== Approval of link:2016-04-27[27 April 2016 Meeting Minutes] -- *approved*
== Working Group and Project Team Updates

=== JWG1/MA (EDIFACT Syntax)

* Nothing to report


=== WG 5 (Representation of dates and times)

* The two ballots closed. K-DN to check with SOSMT and BSI to change vote on ISO 8601–1 & 8601–2 NWIP Ballots from accepting attached CD from 20.00 (Preparatory stage started) to 30.00 (Committee draft (CD) registered).


=== WG 6 (Trusted eCommunication)

* PT1 -- Long term signature profiles for PDF advanced electronic signatures (PAdES)

* PT finished its work, ready for DIS Ballot.


* PT2 -- Trusted Communication Platforms for Electronic Documents

* Progressing, next meeting will scheduled next week.


* PT3 -- Trusted mobile e-document framework

* Meeting scheduled 5 May.






=== Liaison Updates

* Nothing to report


=== MoU/MG Update

* Nothing to report


=== Old Business

* ISO/TC 154 Chairmanship Update

* JFZ to send notice to ISO/TMB about K-DN standing for another term as TC chairperson.


* Business Semantic Thesaurus ISO/TS 16668, formally BSR

* DIN is currently asking its members to act as proposer for the project.




=== New Business

* UN/CEFACT Plenary Update

* Preliminary meeting schedule:

* 17 Oct -- WG 6/PT 1 -- all day
* 18 Oct -- WG 6/PT 2 -- morning
* 18 Oct -- WG 6/PT 3 -- afternoon
* 19 Oct -- WG 5 -- all day
* 20 Oct -- NWIP (TBA) -- morning
* 20 Oct -- WG 5 -- afternoon
* 21 Oct -- ISO/TC 154 Plenary -- all day






=== Other Business

* CAT Membership

* Question was raised about sensitivity of a possible conflict with a member being on the leadership committee of the TC and an external liaison organization. It was agreed to avoid any such conflict that no CAT member should be a member of another internal ISO TC or external liaison leadership group, such as steering groups, executive group and/or bureau. This is to protect the member from being put in a conflicting position to report to either organizations what is being addressed by the other organization in question.




* Next Meeting: *11 May 2016, starting at 14:00 UTC*

