permalink: "cat-draft-minutes-2017-02-15"
date: 2017-02-15T16:36:53Z
categories:
- CAT Minutes
- ETSI
- ISO 14533
- ISO CS
- Liaison
---
= CAT Draft Minutes 2017-02-15

== ISO/TC 154 CAT Conference Call

=== 15 February 2017, 15:00 UTC

Participants::  Klaus-Dieter Naujok (K-DN), Francois Vuilleumier (FV), Mei-Li Chen (MLC)
Excused::  JianFang Zhang (JFZ), Jasmine Chang (JC), Peter Rybar (PR), Bernd Bösler (BB)

<ol>
<li>Approval of Agenda – *approved*</li>
<li>Approval of link:/cat-draft-minutes-2017-02-01[15 February 2017 Meeting Minutes] – *approved*</li>
<li>Working Group and Project Team Updates
<ul>
<li>JWG1/MA (EDIFACT Syntax)
<ul>
<li>Henry supports Brian's suggestion that we should create a RA instead of MA</li>
<li>CAT to review the differences, as defined in the latest ISO Directives, in order to come to a final decision</li>
</ul>
</li>
<li>WG 5 (Representation of dates and times) -- Awaiting ballot closure</li>
<li>WG 6 (Trusted eCommunication)
<ul>
<li>External Liaison with ETSI STF 523
<ul>
<li>Reminder to JC that ETSI needs to send a *request* to ISO/TC 154's Secretariat (JFZ) for WG 6 to nominate a Liaison to work with STF 523. After the request is received, and CAT agrees, a TC 154 ballot needs to be initiate to approve the request and WG 6's proposed liaison person.</li>
</ul>
</li>
<li>PT1 -- Long term signature profiles
<ul>
<li>ISO/DIS 14533-3 Ballot Disposition
<ul>
<li>Ballot Disposition has been distributed via LiveLink</li>
<li>Next step -- Since there were no technical objections, request ISO/CS to publish the ISO 14533-3 as an IS.</li>
</ul>
</li>
</ul>
</li>
<li>PT2 -- Trusted Communication Platforms for Electronic Documents -- *nothing reported*</li>
<li>PT3 -- Trusted mobile e-document framework -- *nothing reported*</li>
</ul>
</li>
<li>WG 7 (Business)
<ul>
<li>Due to K-DN's medical leave, work will be on hold for now
<ul>
<li>PT1 -- Business Semantics Thesaurus -- see above</li>
<li>PT2 -- XMLFACT -- see above</li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
<li>Liaison Updates -- *nothing to report* </li>
<li>Old Business
<ul>
<li>OAGi (Open Applications Group, Inc.) Fast-Track of &#8220;OAGIS – A Specification for an Enterprise Business Canonical Model&#8221;
<ul>
<li>Under final review by FV, BB and KDN before possible submission for DIS (Fast-track)</li>
</ul>
</li>
</ul>
</li>
<li>Old Business
<ul>
<li>TPM -- Henry Cushier
<ul>
<li>Transition underway, very positive progress</li>
</ul>
</li>
<li>“StreaM” Project
<ul>
<li>ISO/TC 184/SC 5 (Interoperability, integration, and architectures for enterprise systems and automation applications) raised the issue that the project should be under their SC not ISO/TC 154</li>
<li>K-DN has been in talk with Henry and for now the ballot will not be recalled.</li>
<li>General view is that this project is larger than &#8220;internal&#8221; workflows as it is all about the &#8220;International Supply Chain&#8221;.</li>
</ul>
</li>
</ul>
</li>
<li>Other Business</li>
<li>Next Meeting: *01 March 2017, starting at 15:00 UTC*</li>
</ol>
]]></content:encoded>


