---
id: iso-34000
name: ISO/WD 34000
title: "Date and time -- Concepts and vocabulary"
status: current
---
:page-liquid:

== Purpose

ISO Recommendations and Standards relating to date and time concepts
have been available since 1971.

This document presents terms and definitions for selected concepts
relevant to date and time concepts and of their representation.

Specifically, the terminology presented in this document:

* serve as a sound basis in the understanding of date and time;
* guide new developments in the field by underpinning mutual understanding; and
* serve as a quick and handy reference for those newly inaugurated to this field.

Most terms in this document were sourced from <<ISO8601-1>> and <<ISO8601-2>>.

== Scope

This document provides a concept system and a standard set of
terminology related to date and time, from basic concepts to those of
their representation.

The scope of the vocabulary provided in this document corresponds to
that of ISO/TC 154/WG 5: Representation of dates and times.


== Who needs this standard?

* This standard provides a standardized set of terminology and concepts of the field of date and time, setting a common understanding for individuals as well as experts with the need to use and communicate date and time concepts.

* This standard's authoritative, common basis of the field of date and time will further define other International Standards relating to date and time, as well as facilitate the interoperation of global systems and processes through the common language for date and time concepts.


== Project leaders

{% assign leader = site.members | where: "member-id", "ronald-tse" | first %}
* link:{{ leader.url }}[{{ leader.name }}] ({{ leader.affiliation }})

