---
id: iso-np-17369
name: ISO NP 17369
title: Statistical data and metadata exchange (SDMX) Revision
status: new
---
// more

== Goal

Revision of link:/standards/isots-173692005[ISO/TS 17369 – Statistical data and metadata exchange (SDMX)], as an International Standard (IS).

== Scope

ISO/TS 17369 was originally published in 2005 as Technical Specification. It specifies a way for Statistical Data and Metadata Exchange (SDMX) in six sections covering the following topics:

* Framework for SDMX standards;
* SDMX information model;
* SDMX-ML schema and documentation;
* SDMX-EDI syntax and documentation;
* an implementer's guide for SDMX; and
* SDMX guidelines for the use of web services.


The revision is to extend to include services-oriented exchange architecture and more complete metadata functionality and to convert the document into an International Standard. The revision builds on the existing ISO/TS 17369 and implementations associated with changes proposed for Version 2 in November 2005 via www.sdmx.org. A disposition log of public comments has been maintained.
