---
id: iso-18262
name: ISO/DTR 18262
title: "Processes, data elements and documents in commerce, industry and administration -- Open data interchange framework"
status: current
---
:page-liquid:

ISO/TR 18262 identifies technical specifications and standards that
are being maintained, developed or given consideration in work
programmes of UN/CEFACT and ISO/TC 154 and strategies that respond
to stakeholder requirements for the open interchange of structured
data in support of administration, commerce and trade.

// more

== Purpose

The purpose of the Open Data Interchange Framework is to define a consistent and timely way to address and resolve issues of gaps, overlaps, and counterproductive standardization efforts through:

. description of a coordinated framework, fostering an integrated work program to meet stakeholder needs in administration, commerce and trade;

. description of a collaboration process, involving business processes and supporting data that facilitate the open electronic interchange of structured data.

== Scope

The overall scope of the Open Data Interchange Framework is:

. the identification of technical specifications and standards that are being maintained, developed or given consideration in work programmes and strategies that respond to stakeholder requirements for the open interchange of structured data in support of administration, commerce and trade;

. identifying relationships and dependencies between the above specifications and standards;

. the identification and definition of what is missing under “a” in order to provide a complete technical framework;

. recommendations concerning ways forward, such as the division of labour to avoid duplication of work and to foster coherence in work programmes and strategies.

////
This Technical Report identifies technical specifications and standards that are being maintained, developed or given consideration in work programmes of UN/CEFACT and ISO/TC 154 and strategies that respond to
stakeholder requirements for the open interchange of structured data in support of administration, commerce and trade. This may include work from SDOs other than ISO and the UNECE.

In particular, this Technical Report presents:
e) ISO/TC 154 and UN/CEFACT’s current work programs to cover requirements for the open interchange of structured data in support of administration, commerce and trade.
f) Duplicate work between ISO/TC 154 and UN/CEFACT's current work programs, as well as work items between ISO/TC 154 and/or UN/CEFACT and its internal and external liaisons' work programs.
g) Gaps that may exist between ISO/TC 154 and UN/CEFACT's work program, to ensure the coverage of all their stakeholders' requirements for the open interchange of structured data in support of administration, commerce and trade.
h) Normative links to other SDO work than has a required dependency to any ISO/TC 154 and/or UN/CEFACT standards.
i) Recommendations on how to eliminate any duplication or gaps identified above in b) & c); and how to manage any required dependencies identified in d), to ensure that any future work on those relevant standards by other SDO's continue to be applicable to ISO/TC 154 and UN/CEFACT’s work programs.
////



////
== Stage

* NP Ballot until 2019/08/07
////

== Who needs this standard?

Facilitating national and international transactions, through the simplification and harmonization of processes, procedures and information flows, and so contributing to the growth of global commerce.


== Project leader

{% assign leader = site.members | where: "member-id", "jianfang-zhang" | first %}

link:{{ leader.url }}[{{ leader.name }}] ({{ leader.affiliation }})
