permalink: /about_us/jwg1
---
= JWG 1 -- EDIFACT Syntax

The *Joint Working Group 1*, formally known as _Joint Syntax Working Group (JSWG)_, started its work in the late 80s to produce the so called version 1 of the EDIFACT syntax (published by ISO as ISO 9735:1988). The membership comprises experts from both UN/ECE and ISO level.

The secretariat was held by Peter Wilson (UK) before in 1998 Bernd Bösler (DE/DIN) took over the responsibility. The convenorship was held for many years by Don Trafford (UK) who died in September 2007 (In memory please see link:http://www.dontrafford.com). The current convenorship is hold by Klaus-Dieter Naujok (DE).

JWG 1's main deliverable is the ISO 9735, EDIFACT – Application level syntax rules, with the following versions:

<ul>
<li>Version 1 – 1988;</li>
</ul>
<ul>
<li>Version 2 – 1990 with minor changes to segments UNG and UNH;</li>
</ul>
<ul>
<li>Version 3 – 1992 with additional character sets (UNOC to UNOF);</li>
</ul>
<ul>
<li>Version 4 – 1998/1999 with:
<ul>
<li>additional batch EDI features;</li>
<li>inclusion of ideographic character sets;</li>
<li>inclusion of the syntax directories;</li>
<li>inclusion of interactive EDI;</li>
<li>inclusion of CONTRL message type;</li>
<li>inclusion of security structures;</li>
<li>inclusion of security message types (AUTACK, KEYMAN);</li>
<li>inclusion of multi format EDI (non-EDIFACT data);</li>
<li>alignment of data field regarding the Y2K issue; and</li>
<li>inclusion of a technique to avoid segment collisions;</li>
</ul>
</li>
</ul>
<ul>
<li>Version 4, Release 1 – 2002 consisting of:
<ul>
<li>*Part 1: *Syntax rules common to all parts</li>
<li>*Part 2: *Syntax rules specific for batch EDI</li>
<li>*Part 3: *Syntax rules specific for interactive EDI</li>
<li>*Part 4: *Syntax and service report message for batch EDI (message type – CONTRL)</li>
<li>*Part 5: *Security rules for batch EDI (authenticity, integrity and non-repudiation of origin)</li>
<li>*Part 6: *Secure authentication and acknowledgement message (message type – AUTACK)</li>
<li>*Part 7: *Security rules for batch EDI (confidentiality)</li>
<li>*Part 8: *Associated data in EDI</li>
<li>*Part 9: *Security key and certificate management message (message type – KEYMAN)</li>
<li>*Part 10: *Syntax service directories</li>
</ul>
</li>
</ul>
Since the last publication in 2002 the JWG 1's work is concentrated on the maintenance of the service codes in process. Appropriate requests (DMRs) are handled by the group who is responsible for updating the UNSL (Syntax directories) and JSWG homepage accordingly (see link:http://www.gefeg.com/jswg[www.gefeg.com/jswg]). According a JWG 1 agreement (2010-10-23) the “2-per-year” update of the Service Code Lists will be performed in alignment with the updates of the corresponding UN/EDIFACT directories.
