permalink: /about_us/ma
---
= TDED Maintenance Agency

== Introduction

The *Trade Data Elements Directory (TDED)* is also known as the United Nations Trade Data Elements Directory (*UNTDED*) and as the International Standard *ISO 7372*. In this Directory, each data element has 2 normative attributes: a 4 digit numerical tag and a free text description/definition. In addition, informative attributes provide e.g. name, character representation, bridging information to the relevant SAD box number, IMO FAL Form, etc.

The ISO Council, in accordance with the http://www.iso.org/iso/standards_development/processes_and_procedures/iso_iec_directives_and_iso_supplement.htm[ISO Directives] (Annex 1G), has established in the late 80's an ISO 7372 Maintenance Agency (ISO 7372 MA). The ISO 7372 MA together with the maintenance function set up by the UNECE WP.4 Working Party on Facilitation of International Trade Procedures (now UN[ECE]/CEFACT), constitute the TDED *Maintenance Agency*, hereafter referred to as *MA*.

The UNECE, through the Trade and Transport Divisions and the ISO through its Central Secretariat jointly provide the Secretariat for the MA. This joint secretariat has appointed a MA *Secretary*.

== Role of the Maintenance Agency

The MA, as authorized by the UNECE WP.4 and by the ISO Council, is entrusted with the following functions:


* To add to or to eliminate data elements from TDED and to assign numeric identifiers (tags) in accordance with the rules provided in Section 5 of TDED;
* To inform interested parties appropriately of such changes, etc.;
* To prepare periodically and disseminate amendment sheets to users in order to allow proper up-dating of TDED;


* To establish as required, in the normal course of work, additional rules for the practical application of the principles for:

** selecting data elements and assigning them a name and a numeric identifier (tag);
** grouping data elements into broad categories;
** the presentation of standard data elements and their use for international trade information interchange.

