permalink: /about_us/ma/ma_links
---
= Relevant links to TDED MA folders/files

* UNTDED – ISO7372 MA website = http://www.iso.org/iso7372ma[JMA website link]


== TDED 2005 edition


UNTDED 2005
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=10416613&amp;objAction=Open&amp;nexturl=%2Flivelink%2Flivelink%3Ffunc%3Dll%26objId%3D7351087%26objAction%3Dbrowse%26viewType%3D1[UNTDED 2005]


ISO 7372:2005
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=10416611&amp;objAction=Open&amp;nexturl=%2Flivelink%2Flivelink%3Ffunc%3Dll%26objId%3D7351087%26objAction%3Dbrowse%26viewType%3D1[ISO 7372:2005]



== Layout Key, TDED


Suite of standards (a)
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=7351005&amp;objAction=Open&amp;nexturl=%2Flivelink%2Flivelink%3Ffunc%3Dll%26objId%3D7351001%26objAction%3Dbrowse%26sort%3Dname[Suite of standards (a)]


Suite of standards (b)
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=7351006&amp;objAction=Open&amp;nexturl=%2Flivelink%2Flivelink%3Ffunc%3Dll%26objId%3D7351001%26objAction%3Dbrowse%26sort%3Dname[Suite of standards (b)]


More on this Suite
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=7334168&amp;objAction=browse&amp;sort=name[More information]



== ISO


ISO main website
http://www.iso.org[ISO Main Page]


ISO/TC 154
http://www.iso.org/iso/standards_development/technical_committees/list_of_iso_technical_committees/iso_technical_committee.htm?commid=53186[ISO/TC154 Page]


== TDED all editions


Scope
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=11421724&amp;objAction=Open&amp;nexturl=%2Flivelink%2Flivelink%3Ffunc%3Dll%26objId%3D10431946%26objAction%3Dbrowse%26viewType%3D1[Scope]


Overview
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=11214675&amp;objAction=Open&amp;nexturl=%2Flivelink%2Flivelink%3Ffunc%3Dll%26objId%3D10482921%26objAction%3Dbrowse%26sort%3Dname[Overview]


Links to previous editions
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=10417266&amp;objAction=browse&amp;viewType=1[Previous Editions]


More info on TDED
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=7409832&amp;objAction=browse&amp;viewType=1[More information]



== JMA


Membership
link:/about_us/jma/membership-of-the-joint-maintenance-agency[Membership of the Joint Maintenance Agency]


Membership Links
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=7345306&amp;objAction=browse&amp;viewType=1[Membership links]


Meetings
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=9728008&amp;objAction=browse&amp;sort=name[Meetings]


Docs & e-mails archives
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=7345413&amp;objAction=browse&amp;sort=name[Docs and email archives]


mailto: cochairs + sec.
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=12241553&amp;objAction=browse&amp;sort=name[Send email to cochairs and secretary]


== UN/ECE


UN/CEFACT
http://www.unece.org/cefact/index.html[UN/CEFACT]


Alignment Project
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=9101510&amp;objAction=Open&amp;nexturl=%2Flivelink%2Flivelink%3Ffunc%3Dll%26objId%3D8361985%26objAction%3Dbrowse%26viewType%3D1[Alignment Project]


Trade Division Secretariat
http://www.unece.org/tradewelcome/trade-home.html[Trade Division Secretariat]


Transport Division Secretariat
http://www.unece.org/trans/Welcome.html[Transport Division Secretariat]

