permalink: /about_us/ma/membership-of-the-tded-maintenance-agency
---
= Membership of the TDED Maintenance Agency

The following inter-governmental and non-governmental organisations are each a full member of the TDED MA (source:
http://isotc.iso.org/livelink/livelink?func=ll&amp;objId=7345306&amp;objAction=browse&amp;viewType=1[TDED 2005 edition, sub-section 2.3 + latest updates]):


* CCC Customs Cooperation Council (see WCO)
* CIT International Railway Transport Committee
* FIATA International Federation of Freight Forwarders Associations
* IATA International Air Transport Association
* ICC International Chamber of Commerce
* ICS International Chamber of Shipping
* IMO International Maritime Organization
* IRU International Road Transport Union
* OASIS Organization for the Advancement of Structured Information Standards: UBL TC Universal Business Language Technical Committee
* UIC International Union of Railways
* UN/CEFACT UNECE (Economic Commission for Europe) Centre for Trade Facilitation and Electronic Business
* UNCTAD United Nations Conference on Trade and Development
* UPU Universal Postal Union
* WCO World Customs Organization, established as CCC

