---
id: jwg1
name: JWG&nbsp;1 (with&nbsp;UN/ECE)
title: EDIFACT Syntax
order: 2
featured_on_home: true
---
:page-liquid:

The EDIFACT Application Level Syntax Rules (ISO 9735) is the main deliverable of the Joint Syntax Working Group (ISO/TC 154/JWG 1). It is was prepared by Technical Committee ISO/TC 154, Processes, data elements and documents in commerce, industry and administration in collaboration with UNECE through UN/CEFACT. It represents the rules at the application level for the structuring of data in the interchange of electronic messages in an open environment, based on the requirements of either batch or interactive processing. In particular these syntax rules serve to support the global UN/EDIFACT standard for EDI. The syntax rules include the definition of the service envelopes, service messages (latest version) and syntax constructs such as the default separator characters and rules for inclusion and exclusion.

// more

NOTE: Please see link:/procedures/sdmr[Syntax Data Maintenance Request Submission and Processing Procedures (SDMR)] for SDMR procedures.

== Scope

The scope of JWG1 also includes the maintenance, update and extend
of ISO 9735.

== History

JWG 1 was established in the late 80's as so called "`Joint Syntax Working Group (JSWG)`" with the UNECE in order to develop and maintain the EDIFACT syntax. Since the publication of the syntax version 1 in 1988, the standard has been revised and amended several times until the current version 4, release 2. With its publication in 2002, the work in JWG 1 is mainly concentrated on the twice-per-year update of the syntax codes directory (in alignment with the EDIFACT user directories) on the corresponding https://www.gefeg.com/jswg/[JSWG website].


== Secretariat

=== Current secretariat

Bernd Bösler (DE/DIN) (1998 - )

=== Previous secretariats

* Peter Wilson (UK) (initial - 1998)

== Convenorship

=== Current convenor

{% assign convenor = site.members | where: "member-id", "yan-zhang" | first %}

link:{{ convenor.url }}[{{ convenor.name }}] ({{ convenor.affiliation }}) (2018 -)


=== Previous convenors

* Don Trafford (UK) (initial - September 2007) (In memory please
see http://www.dontrafford.com)

* Klaus-Dieter Naujok (DE) (September 2007 - 2018)

== Active projects

* link:/projects/iso-9735-11[ISO/NP 9735-11]


== Standards

* link:/standards/iso-9735[ISO 9735 series]
