---
id: wg3
name: WG 3
title: CCTS
order: 3
featured_on_home: true
---

WG 3 was established upon the former "`CCTS`" ad-hoc group of ISO/TC 154 in March 2006.
The purpose is to maintain the ISO/TS 15000-5 "`Core Components Technical Specification, V2.01`"
in close liaison with UN/CEFACT.

The Core Components Technical Specification provides a way to identify, capture and maximize
the re-use of business information to support and enhance information interoperability
across multiple business situations.

// more


== ISO TS 15000-5 (ebXML Core Components Technical Specification, Version 2.01(ebCCTS))

=== Background

ISO TS 15000-5 was first published in 2005, based on the UN/CEFACT publication of the Core Component Technical Specification 2.01. In 2008 it was reviewed and confirmed by ISO/TC 154 for continued publication. In 2011, ISO published Amendment 1 to ISO TS 15000-5, based on corrigendum published by UN/CEFACT.

During the ISO/TC 154 Plenary held in Geneva in September 2010 a small team was tasked with developing this position paper on the future of ISO 15000-5, based on a recommendation from the UK HoD that the TS be made an International Standard.

The secretariat is held by Bernd Bösler (DE/DIN), the convenorship by Mary Kay Blantz (US).

=== Approved Recommendation

* Upgrade 15000-5 to an International Standard.

* Reasons for this choice

** The Core Component Library (CCL) based on this TS is widely used.
** The ISOTC 154 library alignment project has chosen this as the basis for alignment
** The ebMoU Management Group recommends this for global semantic harmonization

* Next Steps

** Make changes to the specification
** Include the published amendment in the document
** Remove references no longer applicable, such as to UN/CEFACT, where appropriate
** Remove the constraint language chapter
** Update or remove the data types
