---
_id: wg4
name: WG 4
title: e-documents
order: 4
inactive: true

intro: |
  WG 4 covers the standardization of e-document concepts and
  semantics to support people, systems and processes involved in
  developing, publishing and using of e-documents.

  WG 4 was closed on 2022-11-26.

scope: |
  Standardization of e-document concepts and semantics to support people,
  systems and processes involved in developing, publishing and using of e-documents.

# organization:
#   convenors:
#     - ronald-tse
#     - james-clark

active_projects:
  - iso-36001

standards:
  - ISO 6422-1:2010

history:
  leadership:
    - ronald-tse
    - james-clark
    - michael-dill
    - sue-probert
    #- bern-bosler

  story: |
    == 2019 to 2022

    WG 4 was established to handle the standardization of electronic documents.
    It has been temporarily closed due to the restart of existing projects.

    == 2006 to 2010

    WG 4 was originally established (formerly as JWG 2 between UNECE and ISO)
    during the UN/CEFACT Forum meeting in Vancouver, March 2006,
    for the purpose of developing an electronic version of the UN Layout Key
    (equivalent to ISO 6422:1985).

    == Previous work

    WG 4 was developing an electronic version of the UNLK (equivalent to ISO 6422:1985). This entails the development of a meta level standard and a methodology for the description of intelligent electronic forms.

    A first New Work Item Proposal (NWIP) was set up as ISO/NP 25557 "`electronic Layout Key`" to be balloted within ISO/TC 154. The appropriate ballot in spring 2006 failed due to that only 3 members agreed to participate. With an amended NWIP a second ballot was started in September 2006 (deadline 2006-12-15), with the result again being negative.

    During the ballots it was realized that there was a lack of information regarding the envisaged standard especially in combination with the existing ISO 6422:1985. Therefore the working group decided, in agreement with its parent body ISO/TC 154, to launch an appropriate ISO process in order to publish the existing ISO 6422:1985 within a framework of a suite where the original ISO 6422 became unchanged Part 1 and the "`electronic Layout Key`" would become Part 2.

    ISO 6422-1 was published in 2010 and another preparatory WI for the progress of the foreseen
    link:/projects/iso-6422-2[ISO 6422-2] was initiated. Due to necessary investigations in September 2011 it was decided to develop first a Technical Report
    (see link:/projects/iso-pwi-tr-6422-3[ISO/PWI TS 6422-3]) regarding the progress of ISO 6422 "`Layout key for trade documents.`" This project shall provide more clarification on an appropriate extension of ISO 6422 for electronic documents as already registered with ISO/NP 6422-2.

    == The UN Layout Key

    The standard(s) should base on the relationship between the underlying core components
    and the presentation aspects of the Layout Key.

    In addition the standard(s) should allow others to derive aligned electronic documents
    based on the electronic Layout Key in a similar way to the development of aligned paper documents
    based on the original UNLK for Trade Documents.

---
:page-liquid:


////
== Collaborative parties

=== CalConnect

https://www.calconnect.org[CalConnect], the Calendaring and Scheduling Consortium, is
a Category A liaison of ISO/TC 154.

CalConnect is focused on the interoperable exchange of calendaring and scheduling information between dissimilar programs, platforms, and technologies. Our mission is to promote general understanding of and provide mechanisms to allow interoperable calendaring and scheduling methodologies, tools and applications to enter the mainstream of computing.

CalConnect's TC PUBLISH is heavily engaged with WG 4 projects, including its contribution to link:/standards/iso-8601-2[ISO 8601-2].

Current collaborative projects include:

* link:/projects/iso-34000[ISO 34000]
* link:/projects/iso-34300[ISO 34300]

=== OASIS

https://www.oasis-open.org[OASIS] is a Category A liaison with ISO/TC 154.

OASIS has a broad technical agenda encompassing cybersecurity, blockchain, privacy, cryptography, cloud computing, IoT, urban mobility, emergency management, content technologies. In fact, any initiative for developing code, APIs, specifications, or reference implementations can find a home at OASIS.

The OASIS community is committed to advancing work that lowers cost, improves efficiency, stimulates innovation, grows global markets, and promotes interoperability. Each project operates independently under industry-leading process and clear IPR policies.

Some of the most widely adopted OASIS Standards include AMQP, CAP, CMIS, DITA, DocBook, KMIP, MQTT, OpenC2, OpenDocument, PKCS, SAML, STIX, TAXII, TOSCA, UBL, and XLIFF. Many of these have gone on to be published as ISO, IEC, or ITU standards. New work is encouraged, and all are welcome to participate.

OASIS members can be found in 100+ countries on virtually every continent. Major multinational companies, SMEs, government agencies, NGOs, universities, research institutions, consulting groups, and individuals are all represented
////
