---
id: wg5
name: WG 5
title: Date and time
order: 5
featured_on_home: true
---
:page-liquid:

WG 5 provides a common platform for all date and time stakeholders, to enable a unified, interoperable of date and time across populations and systems. It publishes the ISO 8601 family of standards in ubiquitous use today.

// more

== Scope

The scope of WG5 is to provide a common platform for all date and time stakeholders, to enable a unified, interoperable of date and time across populations and systems. Specifically, the work involves the standardization of concepts and semantics related to date and time, systems and processes that use or measure date and time, and the interoperability of information systems that utilize date and time.

== Deliverables

* ISO 8601-1:2019 was published on 2019-02-25
* ISO 8601-2:2019 was published on 2019-02-25

== Convenorship

=== Current convenor

{% assign convenor = site.members | where: "member-id", "ronald-tse" | first %}

link:{{ convenor.url }}[{{ convenor.name }}] (CalConnect) (2019/04 - )

=== Previous convenors

{% assign convenor = site.members | where: "member-id", "ray-denenberg" | first %}

link:{{ convenor.url }}[{{ convenor.name }}] (ISO/TC 46) (2018 - 2019/04)
