---
name: ISO 8601-2:2019
type: international
title: "Date and time -- Representations for information interchange -- Part 2: Extensions"
publication-date: 2019-03-25
---

== Introduction

The purpose of this document is to provide a set of date and time
format representations for information interchange beyond those
supported by <<ISO8601-1>>.

There are various concepts and representations that many applications
find useful not supported by <<ISO8601-1>>, including:

* negative values for time scale components;

* qualification of expressions and time scale components;

* set representation of date and time expressions;

* seasons;

* time intervals with open or unknown starts or ends;

* expression of movable days through date and time selection;

* date and time expressions without digit length limits; and

* profiles for specifying feature support amongst ISO 8601 features.


Such concepts are often represented according to various ad-hoc
conventions, and this document aims to provide a standard syntax for
their representation.

The extended representations allow unambiguous interpretation and
enforce the confidence of interoperability and minimize the risk of
misinterpretations and their consequences.

== Scope

This document specifies additional representations of dates of the
Gregorian calendar and times based on the 24-hour clock that extend
the basic rules and composite elements of those defined in
<<ISO8601-1>>.
These representations are specified as character strings for use in
information interchange.
It is also applicable for representing times and time shifts based
on Coordinated Universal Time (UTC).

These extensions include:

* uncertain or approximate dates, or dates with portions unspecified;

* extended time intervals;

* divisions of a year;

* sets and choices of calendar dates;

* grouped time scale units;

* repeat rules for recurring time intervals; and

* date and time arithmetic.

This document excludes the representation
of date elements from non-Gregorian calendars or times
not from the 24-hour clock.
This document does not address character encoding of
representations specified in this document is also not covered.

== References

* [[[ISO8601-1,ISO 8601-1]]], _Date and time -- Representations for information interchange -- Part 1: Basic rules_
