---
standard-identifier: ISO 9735-3:2002
standard-type: international
title: "ISO 9735-3:2002 Electronic data interchange for administration, commerce and transport (EDIFACT) -- Application level syntax rules (Syntax version number: 4, Syntax release number: 1) -- Part 3: Syntax rules specific to interactive EDI"
---
= ISO 9735-3:2002 Electronic data interchange for administration, commerce and transport (EDIFACT) -- Application level syntax rules (Syntax version number: 4, Syntax release number: 1) -- Part 3: Syntax rules specific to interactive EDI

== Abstract
This part of ISO 9735 specifies syntax rules specifically for the transfer of interactive messages to be interchanged between computer application systems. For the transfer of packages in an interactive environment, see ISO 9735-8.

== Revision information
Revises: ISO 9735-3:1998

== Corrigenda, Amendments and other parts

* ISO 9735-1:2002
* ISO 9735-2:2002
* ISO 9735-4:2002
* ISO 9735-5:2002
* ISO 9735-6:2002
* ISO 9735-7:2002
* ISO 9735-8:2002
* ISO 9735-9:2002
* ISO 9735-10:2002

=== Note
This edition is been identified as Syntax Version *4* within the UIB/S001/0002 and Syntax Release *1* within the UIB/S001/0076.

See link:/faq[FAQ page] for the entry describing the differences amongst the various Syntax versions.

