---
name: ISO 8601-1:2019
type: international
title: "Date and time -- Representations for information interchange -- Part 1: Basic rules"
publication_date: 2019-03-25
---

== Introduction

The purpose of this document is to provide a standard set of date and
time format representations for information interchange, in order to
minimize the risk of misinterpretation, confusion, and their
consequences.

This document specifies a set of date and time format representations
utilizing numbers, alphabets and symbols defined in <<ISOIEC646>>.
These representations are meant to be both human recognizable and
machine readable.

This document retains the most commonly used expressions for date and
time of day and their representations from earlier International
Standards in the field, including earlier editions of ISO 8601 and its
predecessors.

== Scope

This document specifies representations of dates of the
Gregorian calendar and times based on the 24-hour clock, as well as
composite elements of them, as character strings for use in information
interchange. It is also applicable for representing times and time
shifts based on Coordinated Universal Time (UTC).

This document excludes the representation
of date elements from non-Gregorian calendars or times
not from the 24-hour clock.
This document does not address character encoding of
representations specified in this document is also not covered.
