---
standard-identifier: ISO/TS 15000-5:2005
standard-type: TS
title: "ISO/TS 15000-5:2005 Electronic Business Extensible Markup Language (ebXML) -- Part 5: ebXML Core Components Technical Specification, Version 2.01 (ebCCTS)"
---
= ISO/TS 15000-5:2005 Electronic Business Extensible Markup Language (ebXML) -- Part 5: ebXML Core Components Technical Specification, Version 2.01 (ebCCTS)

== Abstract
ISO/TS 15000-5:2005 can be employed wherever business information is being shared or exchanged amongst and between enterprises, governmental agencies, and/or other organisations in an open and worldwide environment.

ISO/TS 15000-5:2005 will form the basis for standards development work of business analysts, business users and information technology specialists supplying the content of and implementing applications that will employ the UN/CEFACT Core Component Library (CCL). The Core Component Library will be stored in a UN/CEFACT repository and identified in an ebXML compliant registry.

Due to the evolving nature of the UN/CEFACT Core Component Library, ISO/TS 15000-5:2005 includes material that focuses on the business community doing further discovery and analysis work. Some of the contents of ISO/TS 15000-5:2005 are not typical of this type of technical document. However, they are critical for successful adoption and standardization in this area to move forward.

== Revision information
Revised by: ISO/NP 15000-5

== Corrigenda, Amendments and other parts

* ISO/TS 15000-5:2005/Amd 1:2011
* ISO/TS 15000-1:2004
* ISO/TS 15000-2:2004
* ISO/TS 15000-3:2004
* ISO/TS 15000-4:2004

