permalink: /standards/iso-9735-82002
---
= ISO 9735-8:2002

=== Electronic data interchange for administration, commerce and transport (EDIFACT) -- Application level syntax rules (Syntax version number: 4, Syntax release number: 1) -- Part 8: Associated data in EDI
==== Abstract
This part of ISO 9735 specifies syntax rules for associated data in EDI to be interchanged between computer application systems. This provides a method to transfer data which cannot be carried by means of either a batch or interactive EDIFACT message. The data may be created by other applications (such as STEP, CAD, etc.), and is referred to in this part as associated data.

==== Revision information
Revises: ISO 9735-8:1998

==== Corrigenda, Amendments and other parts
* ISO 9735-1:2002
* ISO 9735-2:2002
* ISO 9735-3:2002
* ISO 9735-4:2002
* ISO 9735-5:2002
* ISO 9735-6:2002
* ISO 9735-7:2002
* ISO 9735-9:2002
* ISO 9735-10:2002

==== Note
This edition is been identified as Syntax Version *4* within the UNB/S001/0002 and Syntax Release *1* within the UNB/S001/0076 for BATCH EDI or as Syntax Version *4* within the UIB/S001/0002 and Syntax Release *1* within the UIB/S001/0076 for Interactive EDI.

See link:/faq[FAQ page] for the entry describing the differences amongst the various Syntax versions.

