---
permalink: /standards/iso-9735-12002
---
= ISO 9735-1:2002

== Electronic data interchange for administration, commerce and transport (EDIFACT) -- Application level syntax rules (Syntax version number: 4, Syntax release number: 1) -- Part 1: Syntax rules common to all parts

=== Abstract
This part of ISO 9735 specifies common syntax rules for the formatting of batch and interactive messages to be interchanged between computer application systems. It includes the terms and definitions for all parts of ISO 9735.

=== Revision information

* Revises: ISO 9735-1:1998
* Revises: ISO 9735-1:1998/Cor 1:1998

=== Corrigenda, Amendments and other parts

* ISO 9735-2:2002
* ISO 9735-3:2002
* ISO 9735-4:2002
* ISO 9735-5:2002
* ISO 9735-6:2002
* ISO 9735-7:2002
* ISO 9735-8:2002
* ISO 9735-9:2002
* ISO 9735-10:2002

=== Note

This edition is been identified as Syntax Version *4* within the UNB/S001/0002 and Syntax Release *1* within the UNB/S001/0076.

See link:/faq[FAQ page] for the entry describing the differences amongst the various Syntax versions.

