---
permalink: /standards/iso-86012004
---
= ISO 8601:2004

== Data elements and interchange formats -- Information interchange -- Representation of dates and times

=== Abstract

ISO 8601:2004 is applicable whenever representation of dates in the Gregorian calendar, times in the 24-hour timekeeping system, time intervals and recurring time intervals or of the formats of these representations are included in information interchange. It includes

* calendar dates expressed in terms of calendar year, calendar month and calendar day of the month;
* ordinal dates expressed in terms of calendar year and calendar day of the year;
* week dates expressed in terms of calendar year, calendar week number and calendar day of the week;
* local time based upon the 24-hour timekeeping system;
* Coordinated Universal Time of day;
* local time and the difference from Coordinated Universal Time;
* combination of date and time of day;
* time intervals;
* recurring time intervals.

ISO 8601:2004 does not cover dates and times where words are used in the representation and dates and times where characters are not used in the representation.

ISO 8601:2004 does not assign any particular meaning or interpretation to any data element that uses representations in accordance with ISO 8601:2004. Such meaning will be determined by the context of the application.

==== Revision information

Revises: ISO 8601:2000

