permalink: /standards/isots-15000-32004
---
= ISO/TS 15000-3:2004

=== Electronic business eXtensible Markup Language (ebXML) -- Part 3: Registry information model specification (ebRIM)
==== Abstract
ISO 15000-3:2004 defines the requirements for the information model for the ebXML registry. The ebXML registry describes objects that reside in a repository for storage and safekeeping. The information model does not deal with the actual content of the repository. All elements of the information model represent metadata about the content stored in the repository. Such information is used to facilitate ebXML-based Business-to-Business partnerships and transactions. The registry information model provides a high-level schema for the ebXML registry. It provides information on the type of metadata that are stored in the registry as well as the relationships among metadata classes. The registry information model defines what types of objects are stored and defines how stored objects are organized. The abstract registry is implemented using one or both of the following concrete bindings: a SOAP binding using the HTTP protocol, or an ebXML messaging service binding. These specifications are compatible with other ebXML specifications.

==== Corrigenda, Amendments and other parts
* ISO/TS 15000-1:2004
* ISO/TS 15000-2:2004
* ISO/TS 15000-4:2004
ISO/TS 15000-5:2005

