---
permalink: /standards/isots-15000-22004/
---
= ISO/TS 15000-2:2004

== Electronic business eXtensible Markup Language (ebXML) -- Part 2: Message service specification (ebMS)
=== Abstract

ISO 15000-2:2004 addresses the requirements for an ebXML message service handler for the eBusiness community. ISO 15000-2:2004 defines a communications-protocol neutral method for exchanging electronic business messages and defines specific enveloping constructs supporting reliable, secure delivery of business information. ISO 15000-2:2004 includes a flexible enveloping technique permitting messages that is independent of the payload, the communications protocol used, and also of any format type. The versatility ensures legacy electronic business systems employing traditional syntaxes (i.e., UN/EDIFACT, ASCX12, or HL7) can leverage the ebXML infrastructure along with users of emerging technologies. Examples using these specifications with HTTP (RFC2616) and SMTP (RFC2821) are included.


=== Revision information

Withdrawn.

=== Corrigenda, Amendments and other parts
* ISO/TS 15000-1:2004
* ISO/TS 15000-2:2004
* ISO/TS 15000-3:2004
* ISO/TS 15000-4:2004
* ISO/TS 15000-5:2005/Amd 1:2011

