---
title: ISO/TC 154 CAT Meeting Minutes 2016-03-30
subtitle: ISO/TC154 CAT Conference Call

cat: CAT Minutes
tags: [ISO CS, Semantic Interoperability, UN/CEFACT]

date: 2016-03-30T15:39:23Z
permalink: "/minutes/2016-03-30/"
---
:page-liquid:

[.participants]
Participants:: Klaus-Dieter Naujok (K-DN), Francois Vuilleumier (FV), JianFang Zhang (JFZ), Mei-Li Chen (MLC), Jasmine Chang (JC)
Excused:: Sue Probert (SP), Peter Rybar (PR), Bernd Bösler (BB)

== Approval of Agenda

approved

== Approval of link:/minutes/2016-03-16[16 March 2016 Meeting Minutes]

*Approved*.

== Working Group and Project Team Updates

=== JWG 1/MA (EDIFACT Syntax)

* Nothing to report


=== WG 5 (Representation of dates and times)

* Both NWIP and CD Ballots have been send out for both ISO 8601 Parts.


=== WG 6 (Trusted eCommunication)

==== PT1 -- Long term signature profiles for PDF advanced electronic signatures (PAdES)

* Still resolving last minute changes before asking for the next ballot.

==== PT2 -- Trusted Communication Platforms for Electronic Documents

* 1st WebEx was cancelled because of low attendance. Next call tomorrow.

==== PT3 -- Trusted mobile e-document framework

* The 1st call was held without proper announcement via LiveLink. The WG Secretariat (JC) was reminded that all meeting announcement, agendas and minutes must be distributed as official WG numbered documents using LiveLink, not only the only collaboration system.



== Liaison Updates

* Nothing to report


== MoU/MG Update

* Nothing to report


== Old Business

=== ISO/TC 154 Chairmanship (2017- )

* Correspond to next call.


=== Business Semantic Thesaurus ISO/TS 16668, formally BSR

* Feedback from ISO CS (Brain) regarding the use of ISO 16668:

** If TC 154 feels that the new standard still basically corresponds to the scope of ISO/TS 16668:2000, then yes, it would be possible for you to continue with "`16668`".

** If TC 154 does this, it will of course need to modify the scope of the proposed NP as appropriate (although a change in title in itself wouldn't be a problem).

** Please note that, as the TS has been withdrawn since 2004, I believe that we would need to include a statement in the Foreword explaining that the original TS was withdrawn for 12 years. On the other hand, if you wish to use a new number for the new standard, then this would be ok as well.

* It was agreed to assign a new number taking into account the fact that there was some opposition to the BSR that may resurface.



== New Business

=== UN/CEFACT Plenary

* CAT reviewed plenary document ECE/TRADE/C/CEFACT/2016/20, UN/CEFACT Prospective Directions, and identified two issues to be passed on to Brian as the ISO HoD to UN/CEFACT:

* Section B. Providing semantic interoperability suggest that "`UN/CEFACT shall be the semantic hub for all of our internal deliverables and will also aim to coordinate and bring together the needs of other organizations.`"

** TC 154 has no issue with UN/CEFACT's internal goals, but it is unclear what the goal is regarding "`bring[ing] together the needs of other organizations`", especially how this works with a Semantic Hub?

* Section H. Enhancing cooperative activities with other standards bodies through bilateral agreements.

* For over three decades UN/ECE (via WP.4 and now UN/CEFACT) and ISO (via TC 154) have enjoyed a close relationship that involve 5 ISO standards (ISO 6422, 7372, 8601, 9735 and 15000-5) that were jointly developed. There is no mention within this section about this special bond, especially since over the last few years this bond has encountered some stress. It would be nice for UN/CEFACT's leadership to ensure ISO/TC 154 that they are still an important partner.



== Other Business



=== Next Meeting

*13 April 2016, starting at 14:00 UTC*

