---
permalink: "/minutes/2016-11-23/"
date: 2016-11-23T22:50:58Z
cat: CAT Minutes
subtitle: ISO/TC154 CAT Conference Call
tags: [Ballots, ISO 14533, ISO 8601, MoU/MG, Semantic Interoperability]
title: ISO/TC 154 CAT Meeting Minutes 2016-11-23
scheduled_time: 23 November 2016, 15:00 UTC

participants: Klaus-Dieter Naujok (K-DN)
  - JianFang Zhang (JFZ)
  - Francois Vuilleumier (FV)
  - Bernd Bösler (BB)
  - Peter Rybar (PR)
  - Mei-Li Chen (MLC)
  - Jasmine Chang (JC)
---
== Approval of Agenda

*Approved*

== Approval of link:/minutes/2016-09-28[28 September 2016 Meeting Minutes]

*Approved*

== ISO/TC 154 Plenary Recap

* Resolutions -- *reviewed*
* Action items -- *reviewed*


== Working Group and Project Team Updates

=== JWG 1/MA (EDIFACT Syntax)

* K-DN updated Brian (ISO/CS) on our decision to stick with an MA instead of RA because of the need to process DMRs that are not code related, such as changes to Data elements, composites and segments within the service directory.
* No response from Brian as of today as he is not in the office.


=== WG 5 (Representation of dates and times)

* Awaiting DIS Ballot announcement from ISO/CS


=== WG 6 (Trusted eCommunication)

==== PT1 -- Long term signature profiles

* Part 3 out for DIS Ballot closing 2016-12-27


==== PT2 -- Trusted Communication Platforms for Electronic Documents

* Next WebEx call planned for early January 2017


==== PT3 -- Trusted mobile e-document framework

* Next WebEx call planned for early January 2017




=== WG 7 (Digital Business)

* Regarding the suggested name change from "`eBusiness`" to "`Business`", it was agreed the definition of business is to broad as it is defined as "`the activity of making, buying, or selling goods or providing services in exchange for money`". Clearly not what the WG is about. Originally as per NWIP it was to be called "`eBusiness`", but BSI objected because of SC32/WG 1 already using it. After a discussion it was agree to call it "`Digital Business`" which is better than just "`Business`" and it does fit the projects that have been assigned to it.

* JF to setup WG 7 on LiveLink.


==== PT1 -- Business Semantics Thesaurus

* Awaiting the creation of WG 7 on LiveLink


==== PT2 -- XMLFACT

* Awaiting the creation of WG 7 on LiveLink






== Liaison Updates

Nothing to report.

== MoU/MG Update

=== Special Conference Call on _Semantic interoperability project_

* Special interest was raised for TC 154's BST work. Inviting MoU/MG members to participate.
* Next meeting is scheduled for 6-7 December



== Old Business

=== OAGi (Open Applications Group, Inc.) Fast-Track of "`OAGIS - A Specification for an Enterprise Business Canonical Model`"

* Awaiting final version from OAGi based on ISO/CS feedback.




== New Business
== Other Business


=== Next Meeting

*21 December 2016, starting at 15:00 UTC*


