---
permalink: "/minutes/2016-03-02/"
date: 2016-03-02T19:50:49Z
cat: CAT Minutes
subtitle: ISO/TC 154 CAT Conference Call
tags: [ISO 8601, Liaison, TC 8, UBL, UN/ECE, WCO]
title: ISO/TC 154 CAT Meeting Minutes 2016-03-02
scheduled_time: 02 March 2016, 15:00 UTC

participants:
  - Klaus-Dieter Naujok (K-DN)
  - Francois Vuilleumier (FV)
  - Jianfang Zhang (JFZ)
  - Mei-Li Chen (MLC)
  - Jasmine Chang (JC)

excused:
  - Bernd Bösler (BB)
  - Sue Probert (SP)
  - Peter Rybar (PR)
---

== Approval of Agenda

*Approved* with the addition of UBL related to JTC 1's ballot under Old Business

== Approval of link:/minutes/2016-02-17[17 February 2016 Meeting Minutes]

*Approved*


== Working Group and Project Team Updates

=== JWG 1/MA (EDIFACT Syntax)

* Nothing to report


=== WG 5 (Representation of dates and times)

* Both NWIP and CD Ballots have been send out for both ISO 8601 Parts.


=== WG 6 (Trusted eCommunication)

==== General

* JC is taking on the WG Secretariat since KATS does not have the resources.
* JFZ to send out a letter ballot for TC 154 to approve JC as WG Secretriat


==== PT1 -- Long term signature profiles for PDF advanced electronic signatures (PAdES)

* Team is still addressing the comments before requesting a new ballot.


==== PT2 -- Trusted Communication Platforms for Electronic Documents

* PT call scheduled for 17 March. Currently the time is rather late for Asian participants, suggest to move the start time 7 hours back.
* JFZ to check with ISO/CS that JC as the convener of WG 5 has a WebEx account for her to schedule WG calls.


==== PT3 -- Trusted mobile e-document framework

* JC to inform Mr. Lee (Project leader) to schedule a PT WebEx call.






== Liaison Updates

* Nothing to report


== MoU/MG Update

* K-DN reported that talking with Brian Stanton (ISO/CS) a solution was found to move forward with circulating both ISO 8601 parts after the ballots close. Assuming both are approved, ISO C/S will work with MoU/MG members to ensure that those that use ISO 8601 do get involved in the work.


== Old Business

=== CAT's comments on UN/ECE's "`Proposed Strategic Framework 2016`"

* No response was received


=== CAT's response to UN/CEFACT Bureau email regarding UN/ECE Recommendation 1

* No response was received


=== ISO Letter to IMO (WCO Data Model)

** K-DN and FV to draft a response to TC 8, for SP to review.




== New Business

=== UN/ECE's comments about misleading CAT minutes 2015-12-09

* K-DN talked with Brain Stanton (ISO/CS) about the UN/ECE concern. It was agreed that the TC 154 minutes did reflect what was said. If UN/ECE or UN/CEFACT disagree that the position communicated during that MoU/MG call were not what should have been said, UN/ECE and/or UN/CEFACT need to inform the MoU/MG with the correct position as related to the publication of UBL 2.1 as ISO/IEC 19845. It is not up to TC 154 to change its minutes because of a disagreement within the UN/ECE and/or UN/CEFACT.


=== MoU/MG Resolution 15/06: Forming a liaison with ISO/TC 292 for its parts of 28000 series

* K-DN to asked WG 6/PT 1 (Peter and Masashi) for feedback and the need for a liaison.




== Other Business



=== Next Meeting

*16 March 2016, starting at 15:00 UTC*

