---
permalink: "/minutes/2016-05-11/"
publish-date: "2016-05-11T22:57:03Z"
categories: [CAT Minutes, ISO 14533, ISO 8601, ISO CS, MoU/MG, Plenary, Semantic Interoperability]
title: CAT Draft Minutes 2016-05-11
---
= CAT Draft Minutes 2016-05-11

== ISO/TC154 CAT Conference Call, 11 May 2016, 14:00 UTC
Participants:: Klaus-Dieter Naujok (K-DN), JianFang Zhang (JFZ), Mei-Li Chen (MLC), Jasmine Chang (JC), Francois Vuilleumier (FV), Bernd Bösler (BB)

== Approval of Agenda

*Approved*

== Approval of link:/minutes/2016-04-27[27 April 2016 Meeting Minutes]

*Approved*.

== Working Group and Project Team Updates

=== JWG 1/MA (EDIFACT Syntax)

Nothing to report.

=== WG 5 (Representation of dates and times)

* ISO 8601 Part 1 & 2 update

* Both NWIP and CD registration was approved.
* WG 5 already disposed of all comments and is preparing the drafts for the CD ballot




=== WG 6 (Trusted eCommunication)

==== PT1 -- Long term signature profiles for PDF advanced electronic signatures (PAdES)

* ISO/CD 14533-3 Update

* A new draft has been prepared for a possible DIS ballot




==== PT2 -- Trusted Communication Platforms for Electronic Documents

* ISO/WD_19626-1 "`TCP for Electronic Documents-Part 1`" Update

* Further meetings are scheduled to finalize the document.




==== PT3 -- Trusted mobile e-document framework

* ISO/WD 20415 "`TMEF`" Update

* Agreement was reached to finalize the document for possible ballot.




== Liaison Updates

Nothing to report.

== MoU/MG Update

Nothing to report.

== Old Business

=== ISO/TC 154 Chairmanship Update

* JFZ to write letter to inform ISO/TMB that SAC is nominating K-DN to a second term as TC Chair.


=== Business Semantic Thesaurus NWIP for TS, formally ISO/TS 16668 BSR

* Germany agreed to propose the NWIP.
* BB and K-DN to draft the NWIP.


=== ISO/TC 154 Plenary Update

* CAT reviewed and agreed to Plenary Draft Agenda.
* JFZ to distribute to membership.


=== ISO/DTR 18262 ODIF (stage 50.00)

* CA agreed to revise the current DTR to serve as a internal framework for ISO/TC 154.
* K-DN agreed to create the first revision to be available for the upcoming plenary.




== New Business

== ISO/CS Objection to disseminate Drafts of both ISO/CD 8601 parts to MoU/MG

* ISO/CS provided TC with a procedure in response to the MoU/MG request to distribute the ISO 8601 NWIP and CD.

* CAT agreed to question the procedure since it does not address the request for CD distribution. Further, the proposed process by the ISO/CS for the internal review of the NWIP request seems unnecessary as it is against the fundamental principle of the MoU to collaborate to eliminate duplications, overlap and conflicts amongst standards.

* K-DN, BB & FV to draft response to ISO/CS.




== Other Business



=== Next Meeting

*25 May 2016, starting at 14:00 UTC*

