---
permalink: "/minutes/2017-02-15/"
date: 2017-02-15T16:36:53Z
cat: CAT Minutes
subtitle: ISO/TC154 CAT Conference Call
tags:  [ETSI, ISO 14533, ISO CS, Liaison]
title: ISO/TC 154 CAT Meeting Minutes 2017-02-15
---
= ISO/TC 154 CAT meeting 2017-02-15

Date::
15 February 2017, 15:00 UTC

[.participants]
Participants::  Klaus-Dieter Naujok (K-DN), Francois Vuilleumier (FV), Mei-Li Chen (MLC)
Excused::  JianFang Zhang (JFZ), Jasmine Chang (JC), Peter Rybar (PR), Bernd Bösler (BB)

== Approval of Agenda

*Approved*

== Approval of link:/minutes/2017-02-01[15 February 2017 Meeting Minutes]

*Approved*

== Working Group and Project Team Updates

=== JWG 1/MA (EDIFACT Syntax)

* Henry supports Brian's suggestion that we should create a RA instead of MA
* CAT to review the differences, as defined in the latest ISO Directives, in order to come to a final decision

=== WG 5 (Representation of dates and times)

* Awaiting ballot closure

=== WG 6 (Trusted eCommunication)

* External Liaison with ETSI STF 523

* Reminder to JC that ETSI needs to send a *request* to ISO/TC 154's Secretariat (JFZ) for WG 6 to nominate a Liaison to work with STF 523. After the request is received, and CAT agrees, a TC 154 ballot needs to be initiate to approve the request and WG 6's proposed liaison person.

==== PT1 -- Long term signature profiles

* ISO/DIS 14533-3 Ballot Disposition

** Ballot Disposition has been distributed via LiveLink

** Next step -- Since there were no technical objections, request ISO/CS to publish the ISO 14533-3 as an IS.

==== PT2 -- Trusted Communication Platforms for Electronic Documents

*Nothing reported*

==== PT3 -- Trusted mobile e-document framework

*Nothing reported*


=== WG 7 (Business)

* Due to K-DN's medical leave, work will be on hold for now

** PT1 -- Business Semantics Thesaurus -- see above
** PT2 -- XMLFACT -- see above



== Liaison Updates

*nothing to report*


== Old Business

* OAGi (Open Applications Group, Inc.) Fast-Track of "`OAGIS - A Specification for an Enterprise Business Canonical Model`"
** Under final review by FV, BB and KDN before possible submission for DIS (Fast-track)


== Old Business

=== TPM -- Henry Cushier

* Transition underway, very positive progress

=== "`StreaM`" Project

* ISO/TC 184/SC 5 (Interoperability, integration, and architectures for enterprise systems and automation applications) raised the issue that the project should be under their SC not ISO/TC 154
* K-DN has been in talk with Henry and for now the ballot will not be recalled.
* General view is that this project is larger than "`internal`" workflows as it is all about the "`International Supply Chain`".

== Other Business

=== Next Meeting

*01 March 2017, starting at 15:00 UTC*
