name: build

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Set up prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev openssl
      - name: Set up snaps
        run: |
          sudo snap install yq
          sudo snap install aws-cli --classic
          sudo snap install node --classic --channel=10/stable
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - uses: actions/checkout@master
      - name: Set up Git submodules
        run: |
          git submodule update --init
          git submodule foreach git pull origin master
      - name: Install Ruby/Bundler dependencies
        run: |
          gem install bundler -v "~> 2"
          bundle install --jobs 4 --retry 3
      - name: Install Node/NPM dependencies
        run: |
          npm install
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build
